### ISSUE TITLE
How to run this judger on Windows ?

### ISSUE THREAD

**Issue by faiyaz26** [DMOJ/judge#1]
Hello, I want to try out this repo of judge on Windows ? How to use it ? Any documentation will be helpful. :+1:

**Comment by Xyene** [comment]
First, you'll need to set up the judge front-end on localhost (https://github.com/DMOJ/site). Setup is just like any Django site.
Then you'll need to compile our wbox sandbox (https://github.com/DMOJ/judge; https://github.com/DMOJ/judge/tree/master/wbox). It compiles with VC. Note that full sandboxing on Windows is not viable - see http://theinvisiblethings.blogspot.co.nz/2014/01/shattering-myths-of-windows-security.html.
Finally, run `main.py <site bridge host> --server-port <site bridge port>`.

If you're not going for a full setup, it's a bit easier. You'd just have to modify the packet handler (see https://github.com/DMOJ/judge/blob/master/packet.py) and stub out any communication with the site server. Then you could just call the judge methods yourself (see https://github.com/DMOJ/judge/blob/master/judge.py#L136) to have a CLI judge. This may be more trouble than it's worth, though - the DMOJ judge is meant to be used in conjunction with the DMOJ site component, like http://dmoj.ca.
