### ISSUE TITLE
Syscall handlers in Executor framework

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#101]
`BaseExecutor` subclasses should have the ability to simply declare advanced syscall handlers, with standard ones provided, like a socket handler that denies all access.

**Comment by Xyene** [comment]
+1, the fact that this isn't possible right now is the only thing keeping the old-style executors around.

**Comment by quantum5** [comment]
The only thing I can think of adding is allowing the same handler to be specified for multiple syscalls in one go.

**Comment by Xyene** [comment]
By and large this has been implemented. Allowing the same syscall handler for multiple syscalls is something that would be useful in only a couple of executors, and if it's ever implemented it should be tracked as a separate ticket (or none at all).
