### ISSUE TITLE
GNU Octave support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#102]

**Comment by WallE256** [comment]
Where do you find all this weird languages?

**Comment by Xyene** [comment]
<https://en.wikipedia.org/wiki/List_of_programming_languages>. Also, ideone :)

**Comment by WallE256** [comment]
Then, coming soon: MATLAB and Q (Equational Programming Language)

**Comment by Xyene** [comment]
Indeed. Mind you, Octave ~= MATLAB: all MATLAB scripts run under Octave, and any incompatibility between the two is considered an Octave bug.

**Comment by Xyene** [comment]
```python
from .base_executor import ScriptExecutor
from judgeenv import env

class Executor(ScriptExecutor):
    ext = '.m'
    name = 'OCTAVE'
    command = env['runtime'].get('octave')
    address_grace = 131072
    test_program = "disp(input('', 's'))"
    syscalls = ['sched_getaffinity', 'socketcall']

    fs = ['.*\.(?:so|m)', '/lib/', '/dev/urandom$', '/sys/devices/system/cpu/online$', '/proc/stat$',
          '/etc/nsswitch\.conf$', '/etc/passwd$', '/etc/localtime$', '/usr/share/', '/usr/lib/', '/etc/fltk/']

    def get_cmdline(self):
        return [self.get_command(), '--no-gui', '--no-history', '--no-init-file', '--no-site-file' ,
                '--no-window-system', '--norc', '--quiet', self._code]

initialize = Executor.initialize
```

`socketcall` feels a bit sketchy; perhaps we should actually check which call(s) it uses and filter based on those.

**Comment by quantum5** [comment]
You have yet to disable `socketcall`.

**Comment by Xyene** [comment]
@quantum5 see <https://github.com/DMOJ/judge/blob/c7e577b0bb2f2768ebba631139f598d0b4ae4c56/executors/OCTAVE.py#L1>
