### ISSUE TITLE
New Executor Framework

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#105]
#49 does not seek to alter the module-based interface of executors. This should change.

Every executor module should offer only the `Executor` class, containing a `classmethod` called `initialize` that returns `True` or `False` to whether this executor is usable. It should also have a `autodetect` method that returns necessary runtime entries in `judge.yml` when possible.

`executors` package would be more sane than its current design. It will keep a private dictionary of executors, and a `load` method that returns this dictionary, initializing all executors if necessary. It will do so by enumerating all modules in the current package that follows `[A-Z0-9]+\.py` and load them, fulfilling #86. This way, importing doesn't cause a huge amount of child processes to be spawned, and other such crazy actions.

The `executors` package will provide `__main__.py` that loads all executors for testing, and provide a script which would generate `judge.yml`'s runtime section.

Finally, old-style executors, i.e. pre-#49, will be unsupported.

**Comment by Xyene** [comment]
The proposed change has been implemented. Anything not done in this ticket will be tracked in new, separate ones.
