### ISSUE TITLE
WBOX shouldn't use C++11

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/judge#108]
VC++ 2008 is the recommended version to use, and it doesn't support C++11

**Comment by FatalEagle** [comment]
It seems that VS express version isn't good enough in general.

**Comment by FatalEagle** [comment]
Everything breaks, it's beyond repair now. Anyone got a good version of wbox?

**Comment by Xyene** [comment]
The wbox [here](http://files.dmoj.ca/.admin/winjudge/) works well enough.

**Comment by quantum5** [comment]
Where did you even hear VC++ 2008 is recommended?
