### ISSUE TITLE
Unbuffered node doesn't work as expected on Windows judges

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#110]
No `pty`.

**Comment by FatalEagle** [comment]
Or does it?

**Comment by quantum5** [comment]
Well on Windows you can always `CreateRemoteThread` and do nasty stuff! :tongue:

**Comment by Xyene** [comment]
The C runtime's [`setvbuf`](https://msdn.microsoft.com/en-us/library/86cebhfs.aspx) can be used to control the buffer size. Though we can't use it to line buffer, `_IONBF` may be used for no buffering, as the example below shows.

Compile as `setvbuf-test.exe`:
```cpp
#include <stdio.h>
#include <Windows.h>
#include <cstdio>

using namespace std;

int main()
{
    setvbuf(stdout, NULL, _IONBF, 0);
    int x = 0;
    while(++x)
    {
        Sleep(500);
        if(x % 6 == 0) printf("\n");
        else printf(".");
    }
    return 0;
}
```

```
import subprocess
import sys

proc = subprocess.Popen(['setvbuf-test.exe'], stdout=subprocess.PIPE)

while True:
    sys.stdout.write(proc.stdout.read(1))
```

**Comment by Xyene** [comment]
This is not worth the effort to fix. A note of this caveat can be made in the documentation.
