### ISSUE TITLE
Java grader handles Unicode source incorrectly (again)

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#116]
```java
// \u000d class test {
// \u000d     public static void main(String[] args) {
// \u000d         System.out.println("Hello, world!");
// \u000d     }
// \u000d }
```

This is perfectly valid Java code, but the judge rejects it with `No public class: your main class must be declared as a "public class"`.

**Comment by quantum5** [comment]
Are you crazy? Where is your `public class`?

**Comment by Xyene** [comment]
Inconsequential, that's just the code I used on Ideone to test the validity of the code. The output is very much the same if you prepend "public".

**Comment by Xyene** [comment]
Relevant Ideone: http://ideone.com/3i0pSH

**Comment by quantum5** [comment]
The problem is not unicode support but rather your use of `\u000d`. `\u000a` works perfectly. https://dmoj.ca/submission/135295

**Comment by Xyene** [comment]
Using CR instead of LF does not work on the judge, though it does obviously work on the server itself.

```
xyene@herculaneum:~$ cat > test.java
// \u000d class test {
// \u000d     public static void main(String[] args) {
// \u000d         System.out.println("Hello, world!");
// \u000d     }
// \u000d }
xyene@herculaneum:~$ javac test.java
xyene@herculaneum:~$ java test
Hello, world!
```

**Comment by quantum5** [comment]
Found bug: `re.MULTILINE` does not consider `\r` a valid line ending and considers the next "line" as part of the inline comment.

**Comment by Xyene** [comment]
This has been fixed for a while.
