### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#117]
http://php.net/manual/en/migration70.new-features.php

**Comment by Xyene** [comment]
Installed on Herculaneum. The PHP5 executor works just fine for PHP7 (only the ini file regex needs a change). Perhaps it's time for `php_executor`?

**Comment by quantum5** [comment]
Agreed.

**Comment by quantum5** [comment]
This is misguided. PHP 7 simply replaces PHP 5 and can use the same executor. We should simply merge the executors and dump PHP 5 judges.

**Comment by quantum5** [comment]
This will be similar to what we plan on doing for Java.

**Comment by Xyene** [comment]
Dropped.
