### ISSUE TITLE
swiftc colored compiler messages

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#119]
Since #118 is somewhat implemented, we can now have colored compiler messages for Swift.

**Comment by Xyene** [comment]
The color appears when ran from terminal, but the ANSI sequences are not generated when the compiler is programmatically invoked. Perhaps we should try passing a TTY.

**Comment by quantum5** [comment]
Should be as easy as passing the slave fd to both stdin and stdout, then set `Popen.stdin` and `Popen.stdout` to `fdopen(master, 'r/w')` as appropriate.

**Comment by Xyene** [comment]
The source of our pain (left is with `stderr` connected to pty, right is without): 

![image](https://cloud.githubusercontent.com/assets/1403503/16541847/a7303c56-405e-11e6-8035-4017e8d2d50f.png)

**Comment by quantum5** [comment]
Is not actually the source.

**Comment by quantum5** [comment]
This works.
