### ISSUE TITLE
Less verbose judge logs

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#120]
It is very hard to monitor a judge when one testcase takes up 7 lines of log output. Logging JSON packets sounded like a good idea, but as it turns out is not optimal.

**Comment by quantum5** [comment]
I really suspect it won't matter too much after we implement #80. At the very least, a fix won't survive it.

But if an inspiration is needed, we can follow the bridge's format, with a little extra data.

**Comment by Xyene** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1403503/14973687/f5e5fc1c-10b8-11e6-894d-480860b93eb8.png)

With the upcoming removal of AMQP, we can just add a little bit more data to regular stdout.
