### ISSUE TITLE
cptbox compilation without cython

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#132]
With the introduction of #128, it is recognized that some ARM judges, e.g. Raspberry Pi, are not powerful enough to run `cython`. We should allow precompiled `_cptbox.cpp` to be used.

**Comment by Xyene** [comment]
Confirmed `cython` runs on rpi1.

**Comment by quantum5** [comment]
Precompiled `_cptbox.cpp` is now allowed. User is responsible for providing the cythonized file.
