### ISSUE TITLE
Extra time for self-test

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#135]
Sometimes, the initial run of an interpreted language takes a long time to initialize, causing the shocker to activate. This is observed on some Linux VMs, and is probably the explanation for `Failed` on initial runs of Windows judge.

Since TLE is not expected to happen for self-test, we can increase the limit to, say, 10 seconds.

/cc @Xyene

**Comment by Xyene** [comment]
I've noticed this too, for PyPy.

**Comment by quantum5** [comment]
It happens surprising often on Windows. Usually all the Windows PyPy, C# on first run, and some of the `RUBY` executors.

**Comment by Xyene** [comment]
This was fixed but not referenced here.
