### ISSUE TITLE
win32k.sys lockdown

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#136]
From <http://dev.chromium.org/developers/design-documents/sandbox>:

> Process mitigation policies can be applied to the target process by means of SetProcessMitigationPolicy.  The sandbox uses this API to set various policies on the target process for enforcing security characteristics such as force enabling high entropy ASLR.

> On Windows 8 and above, a new mitigation policy was added, accessible via called ProcessSystemCallDisablePolicy which allows selective disabling of system calls available from the target process.  On Windows 10 there is an additional policy that can be applied called ProcessFontDisablePolicy.

From <https://docs.google.com/document/d/1gJDlk-9xkh6_8M_awrczWCaUuyr0Zd2TKjNBCiPO_G4/edit>:

> On Windows, system calls are broadly split into two main types, implemented by two separate subsystems in the kernel. First, there are the nt!* calls, which are implemented by ntoskrnl.exe, then there are the win32k!* calls, which are implemented by Win32k.sys.  Win32k calls tend to be associated with the graphics subsystem (which runs in the kernel on Windows, for performance and historical reasons), while ntoskrnl calls are more for the Windows NT api e.g. file access, network, POSIX.

Looking at <http://j00ru.vexillium.org/win32k_syscalls/>, most of the calls have to do with GDI, but there are also a number of calls which submissions shouldn't have access to anyways (e.g., `NtUserGetAsyncKeyState`).

MDSN: <https://msdn.microsoft.com/en-us/library/windows/desktop/hh769088%28v=vs.85%29.aspx>

Should be very simple to add support for.

**Comment by quantum5** [comment]
Keyword: "should". `SetProcessMitigationPolicy` "[s]ets the mitigation policy for the calling process." Very *simply*, we *simply* need to perform the *simple* operation of injecting some *simple* code into the child process, and *simply* do it before it initializes completely.

**Comment by quantum5** [comment]
Implemented through DLL injection.
