### ISSUE TITLE
Drop support for no -c flag

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#139]
Looking in `data/judge` for a judge configuration file is both confusing and antiquated: none of our current installations use it, so the `-c` flag should be mandatory.

@quantum5

**Comment by quantum5** [comment]
"[N]one of our current installations use it" is a lie. Herculaneum still uses it.

**Comment by WallE256** [comment]
And I use it :+1:

**Comment by Xyene** [comment]
*none of our current solutions *should* use it.

**Comment by Xyene** [comment]
Support has been dropped.
