### ISSUE TITLE
Generator cache

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#14]
Some generators take prohibitively long times to generate testdata, and in a contest scenario it would be beneficial to have a cache of generated data so that subsequent submissions run faster. The cache would likely expire after a few minutes, to free resources.

**Comment by quantum5** [comment]
Current workaround is to generate all test data on the judge and store it privately, as done for http://www.dmoj.ca/problem/linked.

**Comment by Xyene** [comment]
The hack is real and pretty nasty.

**Comment by Xyene** [comment]
This no longer is a problem in `judge2`, as on-demand data generation saves swapping to disk and is overall much faster.
