### ISSUE TITLE
Java OLE causes deadlock

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#146]
<https://gist.github.com/Xyene/a955441fa859349ad246>
<https://dmoj.ca/src/214658>

The following code reproduces the issue without OLEing:

```java
import java.io.*;
import java.lang.reflect.*;

public class Brick {
    public static void main(String[] argv) throws Exception {
        Field output = System.out.getClass().getDeclaredField("writer");
        output.setAccessible(true);
        Object writer = output.get(System.out);
        
        Field rek = Writer.class.getDeclaredField("lock");
        rek.setAccessible(true);
        Object lock = rek.get(writer);
        
        System.out.println(writer);
        System.out.println(lock);
        
        synchronized(lock) {
            while(true);
        }
    }
}
```

### Summary
`java.io.FileOutputStream.writeBytes` needs to synchronize a `BufferedWriter`'s lock. On OLE, the judge no longer reads output so `writeBytes` blocks. [JavaSafeExecutor.java#L88](https://github.com/DMOJ/judge/blob/master/java_executor/src/ca/dmoj/java/JavaSafeExecutor.java#L88) flushes the stream on submission exit, which also requires the same lock. Since the lock has not been released, the grading process is deadlocked.

### Solution
Removing the flushing call in the case of shocker activation should not have any adverse effects. Would require a new flag to keep shocked state, and only not flush if the solution TLEd.

**Comment by quantum5** [comment]
Suggested fix: Don't flush when the shocker activates. The normal shocker is `SIGKILL` so this wouldn't make Java unreliable.

**Comment by Xyene** [comment]
Works.
