### ISSUE TITLE
Auxiliary shocker thread for Java

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#149]
Sometimes JVM or executor bugs do happen which cause deadlocks. In these instances, it would be beneficial to have an auxiliary Python-side shocker thread that kills the JVM process a second or so after the time limit is reached.

**Comment by quantum5** [comment]
Oh I thought you were going to suggest an auxiliary shocker thread that shocks the shocker (meta-shocker), and then may be add another meta-meta-shocker to shock the meta- shocker, resulting in `(?:meta-)+-shocker`s.

**Comment by Xyene** [comment]
:+1:

**Comment by quantum5** [comment]
Oh the python shocker idea wouldn't be that much of a hassle either, for it could actually measure the time and memory before it terminates the process.

**Comment by Xyene** [comment]
Superseded by #155.
