### ISSUE TITLE
Checker IR doesn't propagate to site

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#157]

**Comment by quantum5** [comment]
Can a checker even cause IR?

**Comment by Xyene** [comment]
It can cause errors in the bridge if you fail passing arguments, say, to `CheckerResult`. Perhaps a good idea would be to make `CheckerResult` assert types, and make any server-side processing errors appear in the "Bonus information" section too.

**Comment by Xyene** [comment]
Also, bad things can happen [here](https://github.com/DMOJ/judge/blob/master/judge.py#L600): if the checker function throws an exception, [grading simply stops](https://github.com/DMOJ/judge/blob/master/judge.py#L655).

**Comment by Xyene** [comment]
Fixed in `judge2` branch.
