### ISSUE TITLE
Include racket as supported language

### ISSUE THREAD

**Issue by zzh8829** [DMOJ/judge#16]
waterloo first year cs teaches racket exclusively...

**Comment by quantum5** [comment]
It is funny because @Xyene tried to add it before, on an openshift judge.

**Comment by zzh8829** [comment]
and what happened to it?

**Comment by quantum5** [comment]
I think he managed to hit the disk space limit on openshift. I will see if I can get it implemented.

**Comment by quantum5** [comment]
It is rather sketchy that I am writing code to hot patch syscalls.

**Comment by zzh8829** [comment]
I think racket has a built in sandbox library ?

**Comment by quantum5** [comment]
I don't know enough about Racket to write a sandbox, so I am using the standard `cptbox` which we use for all other languages.

**Comment by zzh8829** [comment]
ok good luck. we have a compiler assignment, i kinda want to test my compiler's performance.
Also in general, is it possible to rank solutions by score (calculated based on multiple factors) instead of time?

**Comment by quantum5** [comment]
Solutions are ranked by score. You need a custom checker to give the score, instead of the default 100% for correct, and 0 for incorrect.

**Comment by zzh8829** [comment]
Does indeed triggers segfault (even under security None), but works fine under launch_unsafe. Should I try to implement a racket sandbox.

**Comment by quantum5** [comment]
A racket sandbox is probably the cleaner solution. I am not very proud of the `sys_socketcall` handling on behalf the kernel.

**Comment by quantum5** [comment]
Racket executor now compiles the file to `.zo` before executing it. And it appears to work. If anyone is interested in testing it further, they may do so.

**Comment by quantum5** [comment]
So, the reason Racket didn't work is because Racket uses segfaults in garbage collection. [This debugging guide](https://github.com/racket/racket/blob/d27bf66f1a9847c5252ad00e3d2083807f1d5acd/racket/src/racket/gc/doc/debugging.html) suggests that `SIGSEGV` and `SIGBUS` should be ignored. `cptbox` used to terminate processes that had `SIGSEGV` immediately under the assumption that it has crashed and generates an `RTE`. Who would have guessed that Racket depended on this?

**Comment by zzh8829** [comment]
very interesting indeed.

**Comment by Xyene** [comment]
This has been implemented.
