### ISSUE TITLE
Documentation for compiling and running wbox

### ISSUE THREAD

**Issue by natsukagami** [DMOJ/judge#164]
I would like to use wbox for my personal use, however I've been trying to make / compile it and had no results.
Tried compiling it with Cython - Python 3.5.1 on Windows with Visual C++ Compiler 2015 (VC1900) 64bit amd64. The build_wbox.py script ran successfully, however when I tried to import the module it says
`SystemError: Parent module '' not loaded, cannot perform relative import`
on line 1, `from ctypes import WinError`.

**Comment by quantum5** [comment]
How exactly are you running it? I am not familiar with Python 3, but this [StackOverflow post](http://stackoverflow.com/q/16981921/1090657) may prove useful.

**Comment by natsukagami** [comment]
Can it be compiled with Cython on Python 2? Because I could not get the VS compiler to compile the cpp file, since Python 2's VC version (2008) doesn't have C++11, which Cython compiled the pyx file into.

I installed the latest version of Cython on Python 3
Then ran as follow
- Run `py -3 build_wbox.py` (ran successfully, with no errors) 
- Copy the *.pyd file from `\build\lib.win-amd64-3.5` to `wbox\_wbox.pyd`
- Run `py -3 __main__.py` and get the above error.

**Comment by quantum5** [comment]
You shouldn't run a package from inside. You can `cd ..` and run `python -mwbox` instead to invoke `__main__.py`.

As for using Cython on Python 2, I use Visual C++ 2015 myself, and the build script uses `/MT` to prevent any issues.

**Comment by Xyene** [comment]
In case you just wish to run `wbox` on Python 2, you can download prebuilt `_wbox.pyd` for [x64](http://binaries.dmoj.ca/x64/) and [x86](http://binaries.dmoj.ca/x86/). As you said, `wbox` does not build with the "Microsoft Visual C++ Compiler for Python 2.7"; you'll have to use VC++ 2015.

We've never tried running any segment of the judge with Python 3, and though you might get somewhere with `2to3` your mileage may vary.
