### ISSUE TITLE
Please help. Issues setting up Judge

### ISSUE THREAD

**Issue by shuklarahul142** [DMOJ/judge#167]
I was able to setup site properly. Now I need to setup Judge.
Here is what I did
Copied DMOJ/judge and did: `pip install -r requirements.txt`
Moved to the directory where main.py is there: `cd /home/ubuntu/code/judge/dmoj/`
As mentioned in https://dmoj.readthedocs.io/en/latest/judge/configuration/ ran the command
`python main.py localhost -p 6745 -c /home/ubuntu/code/site/judge_conf.yml`

This is the error I am getting 
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from dmoj.judge import main
ImportError: No module named dmoj.judge`

Could someone please tell me what I have done wrong.
Please help.

**Comment by quantum5** [comment]
We conducted a massive rewrite recently, correct installation instruction is:

1. `python setup.py develop`
2. Run `dmoj <host> -p <port> -c <config>`.

**Comment by shuklarahul142** [comment]
Thanks a lot for the prompt reply!
When I ran `python setup.py develop`
This is what I am getting

`i686-linux-gnu-gcc: error: dmoj/cptbox/_cptbox.cpp: No such file or directory
i686-linux-gnu-gcc: fatal error: no input files`

Did I miss something again?
Please help.

**Comment by Xyene** [comment]
You'll need to `pip install cython` first.

**Comment by shuklarahul142** [comment]
Thanks a lot Xyene!! I will try to get it.
Could this file be checked in as part of this project?

**Comment by quantum5** [comment]
This file is generated from `_cptbox.pyx`. You are supposed to use `cython` to generate it as part of the build process.

**Comment by shuklarahul142** [comment]
Could someone please help me with a sample problem format for a problem? Also where to upload them and how will it be synched with the live website?
Please help.
