### ISSUE TITLE
Checkers are invoked on TLE

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#170]
This can have bad consequences, since sometimes checkers can be very slow. If a submission TLEs, there's no reason to run a checker on it &mdash; TLE masks out WA.

Pros:
* Faster grading

Cons:
* Using a global var to keep track of which case a checker is on will no longer work

To solve the only con, we could add a new kwarg for `testcase_number`.

**Comment by quantum5** [comment]
There is no contractual guarantee that checkers will be run in a certain order. The recommended way to identify the test case is from input and output data. After all, you can do whatever you want with the output data, so might as well give enough context.

**Comment by Xyene** [comment]
This becomes sketchy when you're using the same data subprocessing a third-party checker. A kwarg is much more elegant (and now exists in the form of `case_position`).

**Comment by Xyene** [comment]
This would appear to work.
