### ISSUE TITLE
Compilation Error when using System.Numerics namespace in Mono C#

### ISSUE THREAD

**Issue by Zedronar** [DMOJ/judge#171]
`/tmp/tmp8UzbsS/16bitswonly.cs(2,14): error CS0234: The type or namespace name 'Numerics' does not exist in the namespace 'System'. Are you missing 'System.Numerics' assembly reference?
`

Tried to use Mono.Math alternatively and got:

`error CS0122: 'Mono.Math.BigInteger' is inaccessible due to its protection level`

Any ideas?

Btw, it would be great to be able to use standard C# instead of mono.

**Comment by Xyene** [comment]
Hi, thanks for reporting this.

I've made `dmcs` link `System.Numerics.dll`, so you should be able to run your code. The judge does support regular C# (https://github.com/DMOJ/judge/blob/master/dmoj/executors/CS.py), but it requires a dedicated Windows judge to run (.NET does not run properly under Wine, and our judges run Linux).

**Comment by quantum5** [comment]
Somehow I think you need to manually link such assemblies yourself on Windows too.

**Comment by Zedronar** [comment]
You do. I was just wondering if I could submit solutions in .NET C#, as an unrelated thing.
