### ISSUE TITLE
Debug signal handler

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#173]
We can have a signal handler to help debug hangs or otherwise hard-to-reproduce bugs:

* `SIGUSR1` would print stacktrace of threads similarly to a JVM on `SIGQUIT`
* `SIGUSR2` would drop down into `code.InteractiveConsole`

**Comment by quantum5** [comment]
Umm, other than the fact that signal handlers seems to be invoked at most inappropriate times, and other sketchy POSIX and Python magics to mess with us, and that Python signal handlers are invoked if flags are set by the actual signal handlers by the interpreter, and other such baggage, I don't see a problem.

**Comment by Xyene** [comment]
It's a pretty common use-case, [and it works](http://stackoverflow.com/questions/132058/showing-the-stack-trace-from-a-running-python-application).

**Comment by quantum5** [comment]
I doubt it would do any good if `_cptbox` hangs while holding GIL, but it's not something that is expected to happen very often, as it has not happened after it started working.

**Comment by Xyene** [comment]
Example usage/output:

```
xyene@lemuria:/code/judge$ sudo kill -SIGUSR1 $!
# Thread 140506189178624 (most recent call first):
   File: "/usr/lib/python2.7/threading.py", line 309, in wait
   File: "/usr/lib/python2.7/Queue.py", line 150, in get
   File: "/usr/local/lib/python2.7/dist-packages/watchdog-0.8.3-py2.7.egg/watchdog/observers/api.py", line 359, in dispatch_events
   File: "/usr/local/lib/python2.7/dist-packages/watchdog-0.8.3-py2.7.egg/watchdog/observers/api.py", line 196, in run
   File: "/usr/lib/python2.7/threading.py", line 792, in __bootstrap_inner
   File: "/usr/lib/python2.7/threading.py", line 769, in __bootstrap

... <couple dozen Watchdog threads> ...

# Thread 140507119609600 (most recent call first):
   File: "/usr/lib/python2.7/socket.py", line 336, in read
   File: "/code/judge/dmoj/packet.py", line 74, in _read_single
   File: "/code/judge/dmoj/packet.py", line 64, in _read_async
   File: "/code/judge/dmoj/packet.py", line 92, in run
   File: "/code/judge/dmoj/judge.py", line 247, in listen
   File: "/code/judge/dmoj/judge.py", line 311, in main
   File: "/usr/local/bin/dmoj", line 3, in <module>
```

**Comment by Xyene** [comment]
It works, and should hopefully come in handy for debugging the next horrible bug.
