### ISSUE TITLE
Judge segmentation fault while self-testing

### ISSUE THREAD

**Issue by shuklarahul142** [DMOJ/judge#176]
I am trying running the judge.
Command:  sudo dmoj localhost -p PORT -c /path/to/judge_conf.yml -e C,CPP
It just stops and hangs at and then I have to restart the VirtualMachine:
"Self-testing executors...
Self-testing C:"
I have tried starting judge only for C/CPP/PY2, nothing seems to work and my VM just freezes.
Please someone help.

**Comment by Xyene** [comment]
Some more info towards debugging:

* `uname -a`: `Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux`
* `python -c 'print __import__("platform").architecture()'`: `('64bit', 'ELF')`
* `file dmoj/cptbox/_cptbox.so: dmoj/cptbox/_cptbox.so`: `ELF 64-bit LSB shared object, x86-64...`

The following code was used to debug:

```python
EXECUTOR_DIR = '/code/judge/dmoj/executors'

from dmoj import judgeenv
import re
judgeenv.env['runtime'] = {'g++': '/usr/bin/g++'}
judgeenv.only_executors.add('CPP')
_reexecutor = re.compile('([A-Z0-9]+)\.py$')
from dmoj import executors
print 'Checkpoint 1'
from importlib import import_module
from dmoj.judgeenv import env, only_executors, exclude_executors
import os
executors = {}


# Hack around regular load_executors hanging as well
def load_executors():
    global executors
    __executors = set(i.group(1) for i in map(_reexecutor.match,
                                              os.listdir(EXECUTOR_DIR))
                      if i is not None)
    if only_executors:
        __executors &= only_executors
    if exclude_executors:
        __executors -= exclude_executors
    __executors = sorted(__executors)
    import traceback
    def __load_module(executor):
        try:
            module = import_module('dmoj.executors.%s' % (executor))
        except ImportError as e:
            if e.message not in ('No module named _cptbox',
                                 'No module named msvcrt',
                                 'No module named _wbox',
                                 'No module named termios'):
                traceback.print_exc()
            return None
        return module
    for name in __executors:
        executor = __load_module(name)
        if executor is None:
            continue
        if hasattr(executor, 'aliases'):
            for alias in executor.aliases():
                executors[alias] = executor
        else:
            executors[name] = executor

load_executors()

executors['CPP'].Executor.has_color = False
test = executors['CPP'].Executor('test', '''
#include <iostream>
using namespace std;
int main() {
 cout << "Hello!" << endl;
 return 0;
}
''')
print 'Checkpoint 2'
proc = test.launch(time=2, memory=65536)
print 'Checkpoint 3'
proc.wait()
print 'Checkpoint 4'
print 'Used %dkb memory in %.4f seconds' % (proc.max_memory, proc.execution_time)
```

Output was:

```
Checkpoint 1
Checkpoint 2
Checkpoint 3
Segmentation fault
```

The judge ran out of memory while debugging the child process. `free -m` reports, before running the judge:

```
             total       used       free     shared    buffers     cached
Mem:           995        143        851          0          6         41
```

**Comment by shuklarahul142** [comment]
Faced same issue in new Ubuntu version as well:
`uname -a` : `Linux vagrant-ubuntu-trusty-64 3.13.0-87-generic #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`python -c 'print __import__("platform").architecture()' ` : `('64bit', 'ELF')`
`file dmoj/cptbox/_cptbox.so: dmoj/cptbox/_cptbox.so` : `dmoj/cptbox/_cptbox.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4ae783dac765812e5d8b31eac73603a06d596607, not stripped`

**Comment by Xyene** [comment]
Error was fixed by recompiling a freshly-generated _cptbox.

**Comment by shuklarahul142** [comment]
I am facing the issue again.

The latest code of judge is again failing in following step 
`python setup.py develop`

I think this is because of some recent changes
because when I did reset to last commit which was working, my issue was resolved.
`$ git reset --hard 0520030ced7bffbc1d1c00412624c0205b912f16
HEAD is now at 0520030 Added cap on readstr length.`
