### ISSUE TITLE
Reasonable default executor path

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#178]
Since the configuration file ends up being `/usr/bin/<command>` anyways, we might as well use that as default, using zero-configuration for as many executors as possible.

**Comment by Xyene** [comment]
Rather than this, I'd much prefer some sort of `autoconfig` command &mdash; manually having to specify which executors I want with `-e` is rather painful if I have many things already installed.

**Comment by quantum5** [comment]
You can always disable them with the configuration file.

**Comment by quantum5** [comment]
Superseded by autoconfig as described in #105.
