### ISSUE TITLE
SIGABRT appears to be displayed as SIGSTOP

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#179]
When a submission dies because of something like `std::bad_alloc`, it should be exiting with `SIGABRT`. However, the judge displays it as exiting with `SIGSTOP` (`Stopped (signal)`).

The judge uses `SIGSTOP` internally, but this should never be making its way to the site. Instead, in cases of `std::bad_alloc`, `Aborted` would be the expected feedback on the site.

**Comment by quantum5** [comment]
Could this be related to #183?

**Comment by Xyene** [comment]
It would appear that if a large array that exceeds the memory limit is placed globally, this still occurs.

<https://dmoj.ca/submission/253315>

**Comment by Xyene** [comment]
Summary:

* if a process can't even initially fit in memory, Linux sends it `SIGKILL`
* this happens *after* the process receives (and cptbox handles) the initial `SIGSTOP`, hence `_signal = SIGSTOP` 
* the `SIGKILL` does not make it to the cptbox handler, but it does kill the process, so `returncode = -SIGKILL`

Hence, to check if the process failed to even start because of improperly allocated resources, we can simply do:

```python
process._signal == signal.SIGSTOP and process.returncode = -signal.SIGKILL
```

This should only be `True` in this case, as for regular execution `process._signal == -process.returncode` in the case of abnormal termination.

A point of interest is what we do when the process TLEs and we send `SIGKILL` without the process having experienced a signal in its normal execution &mdash; I believe the above condition would still be true, though I guess we can send in a random signal (`SIGWINCH`?) before `SIGKILL`, so that `process._signal` would not be `SIGSTOP` such that the condition would fail.

There's probably a better way to do this, but the above explains the issue.

**Comment by Xyene** [comment]
This bug has been fixed.
