### ISSUE TITLE
C++ causing protection faults

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#183]
```
Protection fault on: 234 (sys_tgkill)
Arg0: 0x0000000000002d66
Arg1: 0x0000000000002d66
Arg2: 0x0000000000000006
Arg3: 0x0000000000000008
Arg4: 0x000000000000000a
Arg5: 0x00002ba67d5480c0
```

This is new, but seems to be happening to many submissions. Perhaps a recent library update introduced the use of [`tgkill`](http://linux.die.net/man/2/tgkill). From the man page, `arg0` is `tgid`, `arg1` tid, and `arg2` signal. In this case, it would appear that it is signalling itself (0x2d66) with signal 6 (`SIGABRT`).

From the circumstances of the failing submissions, this is looks like some form of `std::bad_alloc`.

We can add a syscall handler in `CHROOTSecurity` that allows `tgkill` so long as `tgid` equals the process id. This problem relates to #77.

**Comment by quantum5** [comment]
Side note: `tgkill` is probably used by the new `libstdc++` due to threading issues with traditional single thread syscalls, similar to how `_exit` invoking `sys_exit_group` instead of `sys_exit`.

**Comment by Xyene** [comment]
This is fixed, and the judges are now displaying `MLE` or `RTE (Segmentation fault)`, as they should.
