### ISSUE TITLE
Source documentation

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#187]
Though recently-written code is generally well-documented, older parts of the judge have scarcely any comments.

This ticket is meant as a catch-all for documentation improvements, until the point where the judge is understandable by people other than those who wrote it.

**Comment by gabrielsimoes** [comment]
You could add small comments to the beginning of files, as a start. I'm having a hard time trying to understand the code, and knowing what each part should do would help a lot. Thanks for this project, by the way!

**Comment by Xyene** [comment]
Hi, thanks for the interest! Indeed, this is something that should eventually get done.

In the meantime, perhaps this (very brief) rundown of which code does that might help you out:

## Sandboxes
* https://github.com/DMOJ/judge/tree/master/dmoj/wbox controls the Windows sandbox implementation
* https://github.com/DMOJ/judge/tree/master/dmoj/cptbox contains the Linux `ptrace(2)`-based implementation
   * this sandbox allows or denies system calls through on a [whitelist basis](https://github.com/DMOJ/judge/blob/master/dmoj/cptbox/chroot.py#L24-L120); runtimes can specify special handlers that'll can entirely change how a syscall operates
* https://github.com/DMOJ/judge/tree/master/dmoj/executors contains executors for actual runtimes; most of the heavily-lifting is done by the sandbox
* executors specify a test program, extension, what extra syscalls they need to operate, and so on... a good example is the [GO executor](https://github.com/DMOJ/judge/blob/master/dmoj/executors/GO.py)

## Grading
* the different graders are located at https://github.com/DMOJ/judge/tree/master/dmoj/graders, and are among the few parts of the code that are well-documented... most of the work is done by the `standard` grader
* https://github.com/DMOJ/judge/tree/master/dmoj/checkers contains checkers used to validate program output, some of which are in C and bound to Python to increase validation speed; none are documented but their names are self-explanatory (and the code is short)

## Configuration
* https://github.com/DMOJ/judge/blob/master/dmoj/judgeenv.py basically manages your judge's `config.yml`, and all queries related to it
* https://github.com/DMOJ/judge/blob/master/dmoj/config.py is a fancy wrapper around a YAML dictionary for some special evaluation that saves a lot of errorchecking elsewhere in the code (example provided)
* https://github.com/DMOJ/judge/blob/master/dmoj/problem.py a representation of a problem's `init.yml` file, it delegates to whatever is needed to handle things like generators, checkers, graders and so on
* https://github.com/DMOJ/judge/blob/master/dmoj/generator.py runs data generators, called from `problem.py`

## Misc
* https://github.com/DMOJ/judge/blob/master/dmoj/judge.py is the main judge "core", what it really does is implement functions required by https://github.com/DMOJ/judge/blob/master/dmoj/packet.py for communicating with the site server (basically, it schedules problems to be graded)
* https://github.com/DMOJ/judge/blob/master/dmoj/cli.py runs a nice command-line interface; see #161 for details 

---

If there's anything in particular you're looking for not covered above, let me know either here or [on Slack](https://slack.dmoj.ca).

**Comment by Xyene** [comment]
This has gotten a lot better since this issue was filed.
