### ISSUE TITLE
syscalls.py rewrite

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#189]
As it, `syscalls.py` is ridiculously hard to maintain. The translator, while fast as a list, does not say at all what each index is. It is also ridiculously hard to add a platform, as for example #128 took hours to add the syscalls.

Hence the following proposal:
- Syscalls will be declared as tables in the `syscalls` directory. Each table will simply write one syscall per line, with the format: syscall id, whitespace, name.
- `syscalls.py` will contain a list of such files, with their index being used as the translated tuple indicies.
- An alias file will be included, in order to support different names that refer to the same syscall. Yes, some calls in `syscalls.py` doesn't use the current name in the linux kernel.
- `syscalls.py` would parse these tables, and generate the same globals as the current version. Obviously, aliased syscalls will be mapped to the exact same internal syscall code.

Before we deploy this new version, we need to verify that all the mappings contain equivalent functionality, i.e. all old global names work, all syscalls are translated, etc.

**Comment by Xyene** [comment]
These can be imported almost-directly from the Linux kernel source.

* [x86 syscalls](http://lxr.free-electrons.com/source/arch/x86/syscalls/syscall_32.tbl?v=3.3)
* [x64 syscalls](http://lxr.free-electrons.com/source/arch/x86/syscalls/syscall_64.tbl?v=3.19)

There is also another list of syscalls that we may scrape from [here](https://w3challs.com/syscalls/). The  may work well with #188, because we could automatically detect which syscalls are unsafe by means of buffers.

**Comment by quantum5** [comment]
Tested ea89d2f876846b6df5040678271301d82205423e on both 32-bit and 64-bit judges, and does not appear to have issues related to syscalls.

**Comment by Xyene** [comment]
```

Protection fault on: 219 (sys_restart_syscall)
Arg0: 0x0000000002e56c2c
Arg1: 0x0000000000000089
Arg2: 0x0000000000000031
Arg3: 0x00002affc60159e0
Arg4: 0x0000000002e56c00
Arg5: 0x00000000ffffffff
Auto-configuring DART:   Failed self-test
```

**Comment by quantum5** [comment]
That's DART being broken by #188.

**Comment by quantum5** [comment]
We should probably provide a reverse translator instead of linear search in `protection_fault`.

**Comment by quantum5** [comment]
@Xyene can you provide the script to generate the FreeBSD table?

**Comment by Xyene** [comment]
This rewrite has been working just fine. I no longer have the script (and it wasn't a very good one in the first place), so I'll be closing this. If ever needed, syscall table generation scripts for FreeBSD can be tracked as a separate ticket.
