### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#192]
Will be a challenge to add.

**Comment by quantum5** [comment]
Just a note that FreeBSD has 550 syscalls, and the `ptbox.h` only defines space for 546. Using the last 4 syscalls will overflow the handler storage.

**Comment by quantum5** [comment]
`helloworld` works on FreeBSD:

Sample session:
```
quantum@dysprosium:~/judge$ dmoj-cli -c judge.yml
Self-testing executors...
Self-testing AWK:    Success
Self-testing BF:     Success
Self-testing C:      Success
Self-testing CPP03:  Success
Self-testing CPP11:  Success
Self-testing PERL:   Success
Self-testing PY2:    Success
Self-testing SED:    Success
Self-testing TEXT:   Success

Running local judge...

dmoj> submit helloworld PY2
print 'Hello, World!'
Start grading helloworld/1 in PY2...
Test case  1 AC [0.026s | 0kb]
Done grading helloworld/1.

dmoj> submit helloworld PY2
print 'Hello, World!!'
Start grading helloworld/2 in PY2...
Test case  1 WA [0.027s | 0kb]
Done grading helloworld/2.
```

**Comment by quantum5** [comment]
Branch tested to still work on linux, while also fixing the race condition with multithreading.

**Comment by quantum5** [comment]
A simple check over the change suggests nothing is broken for Linux. However, we still need to work on 32-bit FreeBSD support, or explicitly prevent its use. We also need to check that threads work on FreeBSD.

**Comment by quantum5** [comment]
We should use `ptrace(PT_LWPINFO)` to replace `PTRACE_O_TRACESYSGOOD`.

**Comment by Xyene** [comment]
After changing a reference to `/proc/self/fd` to `/dev/fd` (which exists on both FreeBSD and Linux), the judge starts up on FreeBSD 10.3. I noticed a hang on initial grading a couple of times, so it's likely there's a race somewhere. Will debug further next time it occurs.

**Comment by quantum5** [comment]
On the other hand, the judge looks functional on Debian GNU/kFreeBSD.

**Comment by quantum5** [comment]
Outstanding bugs:

* `poke_reg` on FreeBSD uses `map_regs_from_linux(&bsd_regs, &bsd_converted_regs)`, where `bsd_regs` is not the original regs, and mapping functions skips many registers. This means the unmapped registers are set to stack garbage.
* Code makes no attempt to report error when used on unsupported FreeBSD archs, i.e. anything that's not `amd64`.

However, it appears that [all changes on `freebsd`](https://github.com/DMOJ/judge/compare/ea89d2f876846b6df5040678271301d82205423e...freebsd) either does not affect linux, are bug fixes, or tested on linux and appears to work. Hence, the branch should be ready to be merged.

**Comment by quantum5** [comment]
Branch is merged.

**Comment by quantum5** [comment]
In all the excitement to get FreeBSD working, we forgot about querying memory usage.

**Comment by quantum5** [comment]
FreeBSD can use `ru_maxrss` from `rusage`. It is supposedly also available on Linux, I wonder why we didn't use it in the first place?

**Comment by quantum5** [comment]
`rusage.ru_maxrss` does not clear on `exec`.

**Comment by quantum5** [comment]
Linux seems to deliberately update `maxrss` to include its previous value:

* see [exec.c](https://github.com/torvalds/linux/blob/84787c572d402644dca4874aba73324d9f8e3948/fs/exec.c#L989)
* [mm.h](https://github.com/torvalds/linux/blob/086e3eb65e3b04d7186f5e527aa6fc375dd5495c/include/linux/mm.h) which has a helper that updates `maxrss`

**Comment by quantum5** [comment]
On FreeBSD, `rusage.ru_maxrss` resets, and appears correct.

**Comment by quantum5** [comment]
OpenBSD is unsuitable for judge use, for it lacks `PT_SYSCALL`.

**Comment by quantum5** [comment]
To avoid the massive conversion function, we can probably use macros.

We can use this macro to make the conversion much simpler:

```c
#define CONVERT_FREEBSD_REG_TO_LINUX(linux_r, bsd_r, name) \
	(linux_r)->name      = (bsd_r)->r_##name
```

Then for portability, we can `#define CONVERT_REG_TO_LINUX CONVERT_FREEBSD_REG_TO_LINUX`. This would allow us to say: `CONVERT_REG_TO_LINUX(linux_r, bsd_r, rbp);`

This is not exactly an improvement, BUT we can use the tiny library [here](https://github.com/swansontec/map-macro) to make this a whole lot more impressive.

With some slight modifications, we produce these set of macros, allowing passing arbitary arguments to the macro being mapped:

```c
#define EVAL0(...) __VA_ARGS__
#define EVAL1(...) EVAL0 (EVAL0 (EVAL0 (__VA_ARGS__)))
#define EVAL2(...) EVAL1 (EVAL1 (EVAL1 (__VA_ARGS__)))
#define EVAL3(...) EVAL2 (EVAL2 (EVAL2 (__VA_ARGS__)))
#define EVAL4(...) EVAL3 (EVAL3 (EVAL3 (__VA_ARGS__)))
#define EVAL(...)  EVAL4 (EVAL4 (EVAL4 (__VA_ARGS__)))

#define MAP_END(...)
#define MAP_OUT

#define MAP_GET_END() 0, MAP_END
#define MAP_NEXT0(test, next, ...) next MAP_OUT
#define MAP_NEXT1(test, next) MAP_NEXT0 (test, next, 0)
#define MAP_NEXT(test, next)  MAP_NEXT1 (MAP_GET_END test, next)

#define STRIP_PAREN(...) __VA_ARGS__
#define INVOKE1(f, x, ...) f(__VA_ARGS__, x)
#define INVOKE(f, a, x) INVOKE1(f, x, STRIP_PAREN a)
#define MAPA0(f, a, x, peek, ...) INVOKE(f, a, x) MAP_NEXT (peek, MAPA1) (f, a, peek, __VA_ARGS__)
#define MAPA1(f, a, x, peek, ...) INVOKE(f, a, x) MAP_NEXT (peek, MAPA0) (f, a, peek, __VA_ARGS__)
#define MAPA(f, a, ...) EVAL (MAPA1 (f, a, __VA_ARGS__, (), 0))
```

This allows us to produce these macros:

```c
#define CONVERT_REG_X(linux_r, bsd_r, name) CONVERT_REG_TO_LINUX(linux_r, bsd_r, name);
#define CONVERT_REG_MAP(linux_r, bsd_r, ...) MAPA(CONVERT_REG_X, (linux_r, bsd_r), __VA_ARGS__)
```

Which allows us to do: `CONVERT_REG_MAP(linux_r, bsd_r, eax, ebx, ecx, edx)`.

The end preprocessed result is:

```c
(linux_r)->eax = (bsd_r)->r_eax; (linux_r)->ebx = (bsd_r)->r_ebx; (linux_r)->ecx = (bsd_r)->r_ecx; (linux_r)->edx = (bsd_r)->r_edx;
```

**Comment by Xyene** [comment]
We should definitely have a macro to convert single registers, but I'm not so sure about the mapping macros - they're cool and might help if we had to map more registers, but as it stands the resultant code would be almost as long as what we have now, albeit with a much increased degree of complexity.

**Comment by Xyene** [comment]
Commit a4912b5 fails on FreeBSD due to the lack of `/proc/pid/cwd`:

```
 Exception OSError: (2, 'No such file or directory', '/proc/46745/cwd') in 'dmoj.cptbox._cptbox.Process._syscall_handler' ignored
Protection fault on: 33 (sys_access)
Arg0: 0x0000000004623800
Arg1: 0x0000000000000000
Arg2: 0x00645f4d54495f00
Arg3: 0x00000008081c3bd8
Arg4: 0x0101010101010101
Arg5: 0x8080808080808080
```

**Comment by quantum5** [comment]
It only fails when it actually uses relative paths, which would be considered unsafe at any rate.

**Comment by quantum5** [comment]
At any rate, since `lsof` works to get the `cwd` of any process on FreeBSD, it must be possible.

**Comment by quantum5** [comment]
`lsof` works by being `setuid` and reading `/dev/kmem`...

**Comment by quantum5** [comment]
However, it seems that [the `procstat` API works](https://github.com/freebsd/freebsd/blob/master/usr.bin/procstat/procstat_files.c#L340).

**Comment by quantum5** [comment]
This sample program gets the `cwd` of any process on FreeBSD.

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/param.h>
#include <sys/queue.h>
#include <sys/socket.h>
#include <sys/sysctl.h>
#include <libprocstat.h>

int main(int argc, char **argv) {
    pid_t pid = atoi(argv[1]);
    struct procstat *procstat = procstat_open_sysctl();
    int kp_cnt;
    struct kinfo_proc *kp = procstat_getprocs(procstat, KERN_PROC_PID, pid, &kp_cnt);
    struct filestat_list *head = procstat_getfiles(procstat, kp, 0);
    struct filestat *fst;

    printf("pid: %d\n", pid);

    STAILQ_FOREACH(fst, head, next) {
        if (fst->fs_uflags & PS_FST_UFLAG_CDIR)
            printf("Found cwd: %s\n", fst->fs_path);
    }
}
```

**Comment by quantum5** [comment]
Implemented obtaining of current directory on FreeBSD. Debian GNU/kFreeBSD has `/proc/pid/cwd`.

**Comment by quantum5** [comment]
The one concerning thing that remains is that the memory usage can sometimes be zero. This has only been observed for `CPP03` and `CPP11`, and the data set is extremely small.

**Comment by Xyene** [comment]
FreeBSD support is, by and large, complete. Noted obscure issues (like 0-memory usages) can be filed as such, but the sandbox is for the most part functioning.
