### ISSUE TITLE
Report runtime versions to site

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#197]
This change would allow the site to auto-generate a listing of runtime versions for each judge, as well as display an up-to-date runtime version in the language dropdown.

This requires a couple changes to the base executor:
- `get_version(self)` returns a tuple containing tuples of length 2 for each relevant runtime. For example, the CoffeeScript executor would return `(('node', '1.2.8'), ('coffee', '1.3.7'))`.
- `get_version_flags(self, command)` should be called once for each relevant runtime (in the CoffeeScript case, `node` and `coffee`). It would be called by `get_version`, and should return the command necessary to produce version output (e.g., `--version`).
- `parse_version(self, command, output)` would return the version for the specified command, given the output from the executor ran with `get_version_flags`. Would be called by `get_version`, and we can create a generally catch-all regex for extracting common version formats.

Languages that don't necessarily have version flags (e.g., Brainfuck or Sed) can simply override `get_version` directly.

Version data can be sent directly after the judge authenticates.

**Comment by quantum5** [comment]
Also suggestion: have the `version` property to cache `get_version` results, unless of course, you actually expect versions to change WHILE the judge is running.

**Comment by Xyene** [comment]
I mean, we could `watchdog` runtime directories, but that's likely overkill.

**Comment by quantum5** [comment]
I doubt your `watchdog` idea will actually work, since watching `/usr/bin` would be pretty silly. Debian for example, symlinks many things like `/usr/bin/python` into `/etc/alternatives`, and `update-alternatives` change which `python` is actually used.

**Comment by Xyene** [comment]
This was a lot more involved to implement than I originally thought, but it's done now. Will leave this ticket open for a little while in case bugs crop up. Aside from this, any UI-related changes really belong in a separate ticket in the site repo.

**Comment by Xyene** [comment]
No bugs have shown up, and this feature works _very_ well live.
