### ISSUE TITLE
Steel Bank Common Lisp support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#198]
Since we now have Clozure Common Lisp, we should use that knowledge for SBCL.

**Comment by Xyene** [comment]
The executor below works, but has obvious issues regarding `execve`, `kill`, and the massive address space. Needs more work.

```python
from dmoj.executors.base_executor import CompiledExecutor
from dmoj.executors.mixins import ScriptDirectoryMixin, NullStdoutMixin


class Executor(NullStdoutMixin, ScriptDirectoryMixin, CompiledExecutor):
    ext = '.cl'
    name = 'SBCL'
    command = 'sbcl'
    command_paths = ['sbcl']
    nproc = -1
    syscalls = ['kill', 'personality', 'execve', ('write', lambda debugger: debugger.arg0 <= 3), 'poll']
    fs = ['/dev/tty$', '/etc/nsswitch.conf$', '/etc/passwd$']
    test_program = '(write-line (read-line))'
    address_grace = 1073741824

    compile_script = '''(compile-file "{code}")'''

    def launch(self, *args, **kwargs):
        self.__memory_limit = kwargs['memory']
        return super(Executor, self).launch(*args, **kwargs)

    def get_compile_args(self):
        return [self.get_command(), '--eval', self.compile_script.format(code=self._code), '--quit']

    def get_cmdline(self):
        return [self.get_command(), '--noinform', '--load', self.problem + ".fasl", '--quit', '--end-toplevel-options']

    def get_executable(self):
        return self.get_command()

    def get_fs(self):
        return super(Executor, self).get_fs() + [self.get_command()]
```

**Comment by quantum5** [comment]
Why? They both implement Common Lisp, like it's literally the same language! It's not like we have any other Haskell implementations, even though they exist.

**Comment by Xyene** [comment]
Sure, but we have Clang as well as GCC. Aside from this, SBCL and CCL both implement (different) non-standard additions that someone, someday, might find useful.

**Comment by quantum5** [comment]
Anyways, massive address space is worked around by using 32-bit version for CCL.

**Comment by Xyene** [comment]
Outstanding issue: SBCL appears to simply refuse running under ulimited memory.

**Comment by Xyene** [comment]
SBCL was recently patched to work with ulimited memory (albeit large). Denying personality change + re-execve makes it randomly fail executing, though. Should be functional after #277.

**Comment by Xyene** [comment]
Years later, it finally works.
