### ISSUE TITLE
`cptbox` improvements.

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#2]
1. Add option to only track process creation and exiting `PTRACE_O_TRACE*`.
2. A `SecurePopen`-compatible class to log only only these events. Useful for example to track languages with builtin sandbox without performance penalty.
3. Port `cptbox` to more platforms, most notably linux x32 to use 64-bit powers with only 32-bit pointers.

**Comment by Xyene** [comment]
:+1:

**Comment by quantum5** [comment]
The said improvements are done. `cptbox` has a null security mode, and support of `x32` and cross-bitness debugging on `x86`. `cptbox` also runs on ARM.
