### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#201]

**Comment by Xyene** [comment]
The executor works. A couple of shortcomings:

* `kotlinc` uses some interesting logic to determine the generated class name, which I've attempted to emulate. I'm not sure if there are more gotchas, though. It also generated a META-INF containing a binary file `main.kotlin_module`, which contains - in some form - the name which may be extracted.
* There's currently no autoconfig. Kotlin runs code through `kotlinc` with `KOTLIN_RUNNER=1` in the environment.
* Ran into the same issue as with Groovy when attempting to use wildcards for files in the security policy.

**Comment by Xyene** [comment]
An option to consider for solving the first and third issues is to include the Kotlin libraries into a jar and just run that. Kotlin provides an option for that: `kotlinc -include-runtime -d <dest>.jar <input>.kt`.

The generated jar has, for a hello world program, a size of 735kb and can be run without requiring any additional `FilePermission`s. In an informal test, running the jar version appears to be consistently faster (by about 0.05 seconds).

Doing this also simplifies the necessary configuration: we can get rid of `kotlin_args` since they'll no longer be relevant.

**Comment by quantum5** [comment]
Kotlin is up and running for almost the length of a pregnancy, so I think we might as well close this.

**Comment by Xyene** [comment]
This isn't actually done, autoconfig is nonfunctional even though the runtime itself works. I think this ticket is the best place to track that.

**Comment by Xyene** [comment]
Screw autoconfig, too complicated when someone can just enter some paths themselves. Kotlin autoconfig, if ever requested, should be a new ticket.
