### ISSUE TITLE
Locking down the Java sandbox

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#202]
Presently, there's just one known issue with the sandbox: if the user halts the JVM without allowing `RuntimeShutdownHook`s to run (there's a function for this), they can then print our UUID along with whatever message they want in `stderr`, and it will be displayed on the site.

This is bad.

An option is to revert to the old system using state files, and 

```
grant codeBase <agent>.jar {
    permission java.io.FilePermission "state", "write";
};
```

With this in place, the worst thing a user could do is exit the VM with an IR but no message: harmless.

**Comment by Xyene** [comment]
I've implemented this, and it works. @quantum5, please review when you have time.

Catches all sketchy cases:

```
dmoj> submit helloworld JAVA7
public class Foo { public static void main(String[] argv) { Runtime.getRuntime().halt(50); } }
:q
Start grading helloworld/1 in JAVA7...
Test case  1 IR [0.154s | 27408kb] (abnormal termination) {WA}
Done grading helloworld/1.
```

```
dmoj> submit helloworld JAVA7
public class OK extends RuntimeException { public static void main(String[] argv) { throw new OK(); } }
:q
Start grading helloworld/2 in JAVA7...
Test case  1 IR [0.148s | 27332kb] (OK) {WA}
Done grading helloworld/2.
```

**Comment by quantum5** [comment]
I doubt signing the sandbox would cause any troubles, since `csbox.exe` is already signed. Unless of course, Java signing turns out to be way worse.

**Comment by quantum5** [comment]
The one thing to consider is whether the submission can change current directory and generate state files anywhere. I do not know enough about Java to predict what would happen.

**Comment by Xyene** [comment]
@quantum5 `System.setProperty("user.dir", "/")` would accomplish that; however our security policies disallow writing to that property.
