### ISSUE TITLE
PTRACE_TRACEME can fail

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#213]
Since it can fail, it would be nice to be able to print a message reporting the fact. It should exit with a well known error code. We know this is not the application's exit code, because if it is, the debugger loop will be run at least once. Otherwise, the parent just hangs on `wait4`, while the child is under `SIGSTOP`, resulting in a cryptic hang.

**Comment by quantum5** [comment]
To clarify, by fail I mean fail at runtime not compile time.

**Comment by quantum5** [comment]
Specifically, we should suggest changing [this setting](https://www.kernel.org/doc/Documentation/security/Yama.txt).

**Comment by Xyene** [comment]
Within Docker, `--privileged` must be passed to Docker too, otherwise `procfs` can't be modified and `ptrace` will still fail, even with 0 yama.
