### ISSUE TITLE
Using exit() in Python 3 submission will result in Invalid Return (NameError)

### ISSUE THREAD

**Issue by bojanbog** [DMOJ/judge#222]
Use case is an exit from multiple nested loops when a solution is found.

For example:
```python
for o in outer_loop:
    for i in inner_loop:
        if solution_found(o, i):
            print_solution()
            exit()
else:
    print('Solution not found.')
```

That would cause `IR (NameError)` when submitted.

Rewriting it like this:
```python
found = False
for o in outer_loop:
    for i in inner_loop:
        if solution_found(o, i):
            print_solution()
            found = True

if not found:
    print('Solution not found.')
```
works but is not very Pythonic.

**Comment by quantum5** [comment]
You want something Pythonic? Try this:

```python
for o in outer_loop:
    for i in inner_loop:
        if solution_found(o, i):
            print_solution()
            break
    else:
         continue
    break
else:
    print('Solution not found.')
```

Just kidding. I will look into it.

**Comment by quantum5** [comment]
After some investigation, it appears that you are trying to use `exit`, which is injected into the builtin namespace by the `site` module. Since the DMOJ does not want to encourage the use of non-standard libraries, which can vary from judge to judge, resulting in inconsistent behaviour, we prevent the import of the `site` module. An acceptable alternative is using `sys.exit()` or just `raise SystemExit`.

**Comment by bojanbog** [comment]
Actually looking into other people's solutions I figured one can simply use `raise SystemExit`.

But it was confusing as hell as this was my first problem submission...

Is there user-editable documentation somewhere where I can note this, I'd be happy to do it.

Thanks!

**Comment by quantum5** [comment]
We have added this to the [tips page](https://dmoj.ca/tips/#python-site).

As for user editable documentation, you can submit pull requests to the https://github.com/DMOJ/docs repository. Contact @WallE256 for details, preferably through our [slack channel](https://slack.dmoj.ca).
