### ISSUE TITLE
PTRACE_TRACEME error on fresh install

### ISSUE THREAD

**Issue by teogenesmoura** [DMOJ/judge#223]
Hi, how are you all?
I've just tried a fresh install of the judge (have never had it on my system) and the installation exits with the following error:

`dmoj/cptbox/ext_linux.h:4:19: error: use of undeclared identifier
      'PTRACE_TRACEME'
    return ptrace(PTRACE_TRACEME, 0, NULL, NULL);
                  ^
1 error generated.
error: command 'gcc' failed with exit status 1
`

I'm running Mac OS X El Capitan v 10.11.1. I realize this is similar to issue #213 , but I'm still not sure on how to fix it. Any help?

**Comment by WallE256** [comment]
As far as i know, at the moment the judge does not come with Mac OS X support. We've looked in the past at this problem, but I'm pretty sure that @Xyene told me that it's not really implementable. Before closing the issue, wait for his or @quantum5's answer.

**Comment by teogenesmoura** [comment]
Oh :( Didn't know about that, thanks!

**Comment by mmun** [comment]
I use vagrant to run it inside of Ubuntu. If you need help with that, drop by the slack shannel: https://slack.dmoj.ca/

**Comment by quantum5** [comment]
Mac OS X support does not exist at this time. The recommended solution is to use a virtual machine to run Linux. Mac OS X support may be added at a future time if there are contributors willing to do so.
