### ISSUE TITLE
Make the GCC executors capable of taking custom macros

### ISSUE THREAD

**Issue by kobortor** [DMOJ/judge#225]
![image](https://cloud.githubusercontent.com/assets/8209554/20645430/330e698c-b42c-11e6-90fb-1cabaa3fb0f1.png)

**Comment by BinAccel** [comment]
For some IOI problems there is a macro defined within the header (e.g for towns it's `towns_h`)

**Comment by quantum5** [comment]
That is ridiculously unreliable, since it's just to prevent multiple `#include`s. For all I care they could have secretly used `#pragma once` instead.

**Comment by BinAccel** [comment]
This has become generalized into "Make the GCC executors capable of taking custom macros"

**Comment by BinAccel** [comment]
@Xyene I think you can close this now.
