### ISSUE TITLE
IE comes up as CE

### ISSUE THREAD

**Issue by BinAccel** [DMOJ/judge#231]
[Submission](https://dmoj.ca/submission/339998)

The Internal Error comes up as a compile error.

[Problem](https://dmoj.ca/problem/ieasce)

This problem was reproduced from [this](https://dmoj.ca/submission/339983).

**Comment by quantum5** [comment]
Fixed in https://github.com/DMOJ/site/commit/99a438112a7ba6b7b35a34db94599fb711e16f3a.
