### ISSUE TITLE
Interactive grader should take strings

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#24]
Well you see, normal grader takes string to `safe_communicate`, checkers also take strings, but these interactive graders, take umm, `cStringIO.StringIO`???

**Comment by FatalEagle** [comment]
Can be fixed by changing Interactor class to perform the conversion in the constructor. But how many interactive problems do we have?

**Comment by quantum5** [comment]
The actual fix is to rewrite the `Interactor` class. The massive error swallowing monster is too scary, and no where does it need to have `cStringIO` when `str` works perfectly fine. Also, we have `ludipq`, `seed2`, and `game1` which use `Interactor`. The other two interactive: `echo` and `shortest1` doesn't use input files.

**Comment by FatalEagle** [comment]
Interactor expects file-like objects to interact with. 3 files seems like an easy change.

**Comment by Xyene** [comment]
This should be fixed as part of #130.
