### ISSUE TITLE
Cached executor framework

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#242]
We should provide some sort of API to cache executors for a defined period of time and postpone cleanup until then. The use-case are compiled executors needed by checkers (offloading heavy computation to C++) or generators.

Compilation for some executors (for example, those using testlib.h) is particularly expensive. In a contest scenario where the same problem is expected to be submitted frequently, recompiling the executor is both inefficient and prohibitively slow (testlib takes up to 20 seconds to compile!)

**Comment by BinAccel** [comment]
The same should be allowed for custom checkers for similar reasons.

**Comment by Xyene** [comment]
As long as an API exists, checkers can use it with no extra work.

**Comment by quantum5** [comment]
How about `get_cached_executor(class, *args, **kwargs)` that looks up the stuff in an LRU cache? Parameters can be decided by command line, or `judge.yml`.

**Comment by Xyene** [comment]
That'd be the way to go. Right now, the generator does something similar in terms of caching one generator for the entire submission.

Also from the looks of it, we don't currently free up the generator (we rely on `__del__` being called, eventually).
