### ISSUE TITLE
LD_PRELOAD-based unbuffering

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#243]
A simple solution to the fact that pseudo-ttys are both a headache and don't currently work.

nobuffer.cpp:

```cpp
#include <stdio.h>

void unbuffer() __attribute__((constructor));

void unbuffer()
{
    setvbuf(stdout, NULL, _IONBF, 0);
}
```

Compile with `gcc -shared -fPIC -o nobuffer.so nobuffer.cpp`, and pass in `LD_PRELOAD=nobuffer.so` to user submissions. The compilation step can be done in `setup.py`.

This will force an unbuffered mode for all languages depending on `libc` for IO. This excludes languages like Python, which handles their own (Python buffering is already handled separately by the judge), but includes all languages compiled with GCC. It also does not include Pascal, which does not link `libc`, but who uses Pascal?

![image](https://cloud.githubusercontent.com/assets/1403503/23495254/9dc53702-fee5-11e6-8a8c-b245f08b4493.png)

With this change implemented, we could easily support unbuffered IO for ~97% of the languages used by volume. The current pty-based implementation can be gutted.

**Comment by Xyene** [comment]
This is functional and passes all unit tests.

**Comment by quantum5** [comment]
I hesitate to conclude this will not break any non-libc languages.
