### ISSUE TITLE
Checkers take longer than submission

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#25]
For linked list, the checker takes longer than the submission itself to check the data.

Some profile data:

```txt
name                                  ncall  tsub      ttot      tavg
..judge/checkers/standard.py:1 check  25     20.60029  39.94269  1.597708
```

The submission itself takes 7.69s. This is clearly not acceptable. I suggest we start porting checkers to C.

**Comment by FatalEagle** [comment]
C++ is more useful if you want non-trivial checkers.

**Comment by quantum5** [comment]
C and C++ co-exist nicely.

**Comment by quantum5** [comment]
Wrote one checker in C, hopefully correct:

https://gist.github.com/quantum5/97d3ed3c02dae32c1d0a

**Comment by quantum5** [comment]
Tested 15.3 MB of identical data obtained from a test case, and the results:

```
Python: 0.777343606001
C: 0.0394724266789
```

The time is the minimum time each took out of 15 runs. 20x speed up it would seem.

**Comment by quantum5** [comment]
New benchmark result:

    name                                  ncall  tsub      ttot      tavg
    ..udge/checkers/standard.py:18 check  25     0.000123  0.488669  0.019547

**Comment by quantum5** [comment]
In practice, the speed up seems higher than 20x: it's 82x.

**Comment by quantum5** [comment]
Open a new ticket if there is a demand to port other checkers into C/C++.
