### ISSUE TITLE
Executable size limit

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#26]
We can set `RLIMIT_FSIZE` to limit the maximum file size a compiler can possibly create. However, setting this limit in the judge process is not a trivial matter. A clean solution requires a script which sets the limit and `execve`s the compiler, which would require a utility function to spawn compilers as this only works on *nix. The helper might also need to catch `SIGXFSZ` exit and raise compile error as appropriate.

Needless to say, this has no priority.

**Comment by quantum5** [comment]
Wait why did no one suggest `preexec_fn`? It couldn't possibly be that bad to simply call `setrlimit`, could it?

**Comment by Xyene** [comment]
This appears to work, and compilers seem to handle `SIGXFSZ` fine, as shown in the following session (the limit is 128mb, which is 33554432 `dd`s).

```python
dmoj> submit helloworld NASM
section .data
    big times 40000000 dd 0
:q
Start grading helloworld/2 in NASM...
Failed compiling submission!
/usr/bin/ld: warning: cannot find entry symbol _start; not setting start address
/usr/bin/ld: final link failed: No space left on device
Done grading helloworld/2.

dmoj> submit helloworld NASM
section .data
    big times 30000000 dd 0
:q
Start grading helloworld/3 in NASM...
Test case  1 RTE [0.002s | 4kb] (Segmentation fault) {WA}
Done grading helloworld/3.
```
