### ISSUE TITLE
dmoj-cli improvements

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#261]
## New commands

- [x] `diff <submission 1 or filename> <submission 2 or filename>`
    * Use [`difflib`](https://docs.python.org/2/library/difflib.html) to generate diff
    * Syntax-highlight ANSI [with Pygments](https://docs.python.org/2/library/difflib.html)
    * Alternatively, write both parameters to a file, then [`subprocess`](https://docs.python.org/2/library/subprocess.html) `git diff <file a> <file b>` if `git` is installed (more user-friendly if `git` is installed)
        * Is it even worth implementing `difflib`/`pygments` fallback if you already need `git` to install DMOJ? Probably not, unless anyone thinks otherwise.
- [ ] `explain <problem code>`
    * Evaluates all dynamic keys / other YAML formatting, and prints it out to `stdout` syntax-highlighted by Pygments
- [x] `show <submission id or filename>`
     * Outputs the syntax-highlighted parameter, with Pygments

## Improvements to old commands
- [x] If the `$EDITOR` environment variable is set,  `submit` should create a `tempfile` with an appropriate extension, then subprocess `$EDITOR <tempfile name>` for editing, instead of requesting input via `stdin`.
- [x] Make `language` parameter to `submit` optional. If no language is passed, guess the language based off file extension of given file (`language` must be provided when entering data through `stdin`).
   * Map some default cases manually, i.e. `{.py: Python 2, .cpp: get_latest_cpp(), .java: get_latest_java()}`
      * Populate this with sensible defaults for well-known languages
   * For the rest, fetch executor by extension, e.g. for Python 3, the extension `py3` must be used
- [x] If `$EDITOR` is set, allow editing of submission on `resubmit` command (write to file of appropriate extension, open editor, read back contents)
- [x] To support these changes, if `$EDITOR` is not defined, output a `startup_warning`

**Comment by quantum5** [comment]
@Xyene Why do you need `git diff` instead of the normal `diff` command?

**Comment by Xyene** [comment]
@quantum5 has nicer colors by default.

**Comment by Xyene** [comment]
This is complete, bar some TODO's left in the code for a future date.
