### ISSUE TITLE
Support cptbox setting personality before execve

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#277]
http://man7.org/linux/man-pages/man2/personality.2.html

`ADDR_NO_RANDOMIZE` in particular would be a good idea for more consistent segfault behaviour. Plus, it'd get runtimes like `SBCL` running without hacks.

Should be configurable through a `personality` field in each executor, with `ADDR_NO_RANDOMIZE` as a default.

It can return `EINVAL`, in which case we should log but continue anyway.

**Comment by Xyene** [comment]
This is done.

**Comment by phoe** [comment]
On SBCL 1.4.5-debian I get the following after running `dmoj-autoconf`:
```
Auto-configuring SBCL:   mmap: Cannot allocate memory
mmap: Operation not permitted
fatal error encountered in SBCL pid 1685(tid 0x1555555456c0):
unexpected mmap(0, 28704768, ...) failure
```

**Comment by phoe** [comment]
Same thing with CCL:
```
Auto-configuring CCL:    minimal initial mmap: Cannot allocate memory
Failed self-test
```

**Comment by Xyene** [comment]
You can try playing around with the `address_grace` parameter https://github.com/DMOJ/judge/blob/master/dmoj/executors/SBCL.py#L18, and perhaps also define `test_memory = something > 65536` for those particular executors.

**Comment by phoe** [comment]
Fixed after setting `test_memory` to 20 MB. I'll be playing around with that value. Thanks!

**Comment by Xyene** [comment]
That value is in kilobytes, are you sure it's working after setting the memory limit _lower_ than the default of 64MB?

**Comment by phoe** [comment]
Wait, it's already in kilobytes? In this case I set it to 20 GB, woops.~

Still, it works with 128 MB. Let me check more.

**Comment by phoe** [comment]
96 MB works as well and I'll keep it that way. Thanks!

**Comment by phoe** [comment]
One more question - I just tried sumitting a program to be run via SBCL and I get invalid return value on each test run; it means that SBCL is crashing for me. Where can I find logs from these crashes?

**Comment by Xyene** [comment]
You can submit the same program via `dmoj-cli`, in which case the `stderr` of the submission will be visible. There is currently no option to see this from the site interface.

**Comment by phoe** [comment]
I can't figure out how to submit anything into the local judge. `dmoj-cli` runs fine, but `dmoj> submit problemname sbcl /tmp/foo.lisp' errors with `invalid file name`.
