### ISSUE TITLE
Unbuffered I/O for interactive problems

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#28]
A certain online judge doesn't require flushing for interactive problems. A ~~wild guess~~ scientific analysis suggests that they present `pty` devices for `stdin` and `stdout`. This can be arranged on *nix through the use of the [`pty` module](https://docs.python.org/2/library/pty.html)'s `openpty()` in place of `os.pipe()`.

**Comment by FatalEagle** [comment]
"online judge" more like "contest platform"

**Comment by Xyene** [comment]
For the Java executor, `UnsafePrintStream` will have to be modified.

**Comment by quantum5** [comment]
Just a note that has nothing to do with implementation:

With a pty, write to `stdin` would actually write to `stdout`. This is observable on normal linux consoles, try `os.write(0, 'Hello, World!\n')`.

**Comment by quantum5** [comment]
With #49 we can probably add support for this rather easily.

**Comment by Xyene** [comment]
Works perfectly on `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`. Herculaneum and Excalibur show no issues, Durandal (running Wheezy and an older kernel) fails with an IOError.

TODO:
* Python reopens the streams with a 64k buffer
* Java does some... magic

**Comment by quantum5** [comment]
I suppose the python loader can simply do `isatty()` to determine if there is a need to reopen.

**Comment by Xyene** [comment]
We can actually pull something similar for Java: `System.console()` will be not-null if `isatty(stdin) && isatty(stdout)`. If we find that this is the case, we can unbuffer System.out.

**Comment by Xyene** [comment]
This works (though none of our interactive problems are functional).
