### ISSUE TITLE
Multiprocessed judge race condition

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#283]

**Comment by quantum5** [comment]
This is not a race condition. This is just code sending too many problem updates, preventing the acknowledgement from being sent.

**Comment by quantum5** [comment]
While the actual race condition causing the "judge seems dead" message should be fixed, there are more reentrancy issues that breaks things like logging.

**Comment by quantum5** [comment]
The problem should be fixed by throttling the signalling speed, although it can still be triggered if you signal in a tight loop, in which case it's either sysadmin incompetence, or system pwned. In both cases, you have bigger things to worry about.

**Comment by quantum5** [comment]
I think this is fixed.
