### ISSUE TITLE
How to load dist-packages in python executor

### ISSUE THREAD

**Issue by thangdnsf** [DMOJ/judge#294]
Hi all, I would like to import third-library in the judge. I installed them into dist-packages of python and test on the servers was okay, but not working in judge with error: **IR-ImportError**
And I removed 'S' in reget_cmdline function to Disable site module for speed (no loading dist-packages nor site-packages) and still not okay and error

> return [self.get_command(), '-B',self._loader, self._code]

Help me!

**Comment by quantum5** [comment]
Simply define `extra_fs` in judge.yml specifying a list of regular expressions that will match all the extra files python will have to access. Finding the correct regular expressions is left as an exercise for the reader.

**Comment by thangdnsf** [comment]
i don't understand! can you tell me more detail?
Thanks

**Comment by Ali-Toosi** [comment]
Could you provide a bit more detail for this? How does this work with loading pip packages? Or feel free to just point me to some documentation about it
