### ISSUE TITLE
Clang/GCC `-march=native` fails on some ARM platforms

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#303]
Older versions of GCC on Raspbian as well as Clang 3.8 fail on some ARM platforms when `-march=native` is specified:

```
clang: error: the clang compiler does not support '-march=native'
```

We currently specify `-march=native` unconditionally (there's a half-working hack for ARM in `gcc_executor`). We should do a test run with `-march=native` to detect if it is supported, and if not fall back to:

* config `runtime.gcc_march`/`runtime.clang_march`
* no `march`

This should also be documented somewhere; https://github.com/DMOJ/docs/issues/37 would be a good place.

**Comment by quantum5** [comment]
I dispute the assertion that the ARM hack is half-working, since that is to catch the ridiculous gcc bug where `-march=native` simply crashes during compile on old Raspbian, with only an obscure message.

**Comment by quantum5** [comment]
Is this done?

**Comment by Xyene** [comment]
Yes, however the branch containing the changes is not merged into master yet, so the ticket is still open.

**Comment by quantum5** [comment]
Was merged a while ago.

**Comment by zertyz** [comment]
Still not working -- clang-7: error: the clang compiler does not support '-march=native'

I'm running on a ArchLinux Raspberry Pi2:

clang version 7.0.0 (tags/RELEASE_700/final)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

The same version of clang correctly compiles the code (with -march=native) on an ArchLinux Raspberry Pi 1 box:
clang version 7.0.0 (tags/RELEASE_700/final)
Target: armv6l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

**Comment by Xyene** [comment]
@zertyz did you use the autoconfig tool? What does your judge config look like?
