### ISSUE TITLE
how can I use the dmoj-cli to judge a problem?

### ISSUE THREAD

**Issue by shunminli** [DMOJ/judge#306]
I build a problem like **_Normal Cases_**   
then  I want to use the dmoj-cli to judge this problem
What should I do?

reference:
https://docs.dmoj.ca/en/latest/judge/problem_format/
https://docs.dmoj.ca/en/latest/judge/linux_installation/#configuring-the-judge

**Comment by shunminli** [comment]
@quantum5 @Xyene

**Comment by Xyene** [comment]
You can type `help` for a list of commands; the one you are probably looking for is `submit`, see `submit --help` for more details.

**Comment by shunminli** [comment]
thx very much.

**Comment by shunminli** [comment]
can I commit some code to build a rpc server? @Xyene

**Comment by quantum5** [comment]
Feel free to fork the repository and add in your changes. Depending on how good of an RPC server you build, it may be merged.

**Comment by shunminli** [comment]
okay, thx very much
