### ISSUE TITLE
`os.getloadavg` isn't available on all Unix

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#308]
```
os.getloadavg()

    Return the number of processes in the system run queue averaged over the last 1, 5, and 15 minutes or raises OSError if the load average was unobtainable.

    Availability: Unix.
```

Surprisingly, "Unix" does not include "weird" systems like Android, where the lack of `getloadavg` causes us to load in Windows' perfmon, which obviously fails.

**Comment by quantum5** [comment]
We should simply fallback to reading `/proc/loadavg`.
