### ISSUE TITLE
server resources usage per judge request

### ISSUE THREAD

**Issue by aliir74** [DMOJ/judge#310]
Hi all.
I want run dmoj for a student festival that have up to 200 students. I want use your judge for many exercises & two contests but didn't see anywhere what server resource requirement per judge request.
Where is this document?

**Comment by Xyene** [comment]
This is a difficult question that doesn't have a single answer, and is more dependent on the type of contest you're running than anything else.

Individual DMOJ judge hosts _can_ run on as few resources as provided by e.g. a Raspberry Pi, so it's up to the contest organizer to determine how many resources to provision judges with. For reference, we typically run contest judge hosts on machines with 1GB RAM, and ~Intel Xeon E5 processors (i.e., what you typically get from online VPSes like DigitalOcean, OVH, etc.). Naturally if your contest's problems require larger memory limits, judge hosts would need to be scaled appropriately.

It's also important to take into account how long your problems take to grade. For example, you'll need more hosts for a contest where correct solutions can take several minutes to judge (e.g. IOI-style hundreds of testcases), and fewer if solutions finish quickly. In a typical 200 contestants in 3 hour window contest, you're looking at a peak submission rate of 2-3 submissions per second (again, this is highly dependent on how your contest is structured), so you can do the math based on your scenario.

On the site end, for 200 contestants you probably don't need to worry (e.g., a 8GB / 4 core server is likely enough), but for large loads, splitting up the database server from the frontend template rendering can provide significant speedups. For large contests, we usually run one 4GB / 2 core template rendering server and one 8GB / 4 core database server. You can do with less, but a setup like this provides a nice safety buffer (and allows you to quickly spin up another frontend server from an image in case of unexpectedly high load).

**Comment by aliir74** [comment]
@Xyene Thanks for your help :)

**Comment by Xyene** [comment]
No problem, and good luck!
