### ISSUE TITLE
PY2 does not pass self-test

### ISSUE THREAD

**Issue by joonas-yoon** [DMOJ/judge#314]
I just enter the commands on [this installation](https://dmoj.readthedocs.io/en/latest/judge/linux_installation/#installing-the-prerequisites)

but i got following log when i entered `dmoj-autoconf`:

```
(env) joonas@ubuntu ~/judge $ dmoj-autoconf
...
Auto-configuring PRO:    Failed to find "swipl"
Auto-configuring PY2:    Traceback (most recent call last):
  File "/tmp/tmp5S02hr/-loader.py", line 1, in <module>
    import runpy, sys, os
ImportError: No module named runpy
Failed self-test
Auto-configuring PY3:    Using /usr/bin/python3.5
Auto-configuring PYPY:   Using /usr/bin/pypy
Auto-configuring PYPY3:  Failed to find "pypy3"
...
```

When I try `python -m pip install runpy` I still get:
```
  Could not find a version that satisfies the requirement runpy (from versions: )
No matching distribution found for runpy
```

What can i do?

worked on Ubuntu 16.04 LTS

**Comment by kiritofeng** [comment]
The judge's `autoconf` currently doesn't work with `virtualenv`. To use the Python 2 runtime, you'd need to manually enter the path.

**Comment by joonas-yoon** [comment]
Thank you for your help. i solve it.
