### ISSUE TITLE
can not compiled correctly

### ISSUE THREAD

**Issue by wangleigpt** [DMOJ/judge#317]
when i install dmoj using 'pip -install -e .' as you listed, the compiler gave this message:    
"d:\oj\dmoj\judge\dmoj\wbox\firewall.h(8) : fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory"
OS: windows 7 with vc for python  and windows sdk installed

**Comment by quantum5** [comment]
`wbox` requires ATL to compile. Please follow https://docs.dmoj.ca/en/latest/judge/windows_installation/ for proper instructions. Obtaining ATL, configuring VC12, or getting the precompiled binaries is left as an exercise for the reader.
