### ISSUE TITLE
Protocol configurability

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#32]
Or something among those lines. TCP packets in async node.js are just too painful.

**Comment by Xyene** [comment]
Or possibly terminating packets with a special character.

**Comment by quantum5** [comment]
You can already do that with a packet manager subclass, but there are better solutions. TCP packets are only as painful in node.js as you make it. Simply store the current length as a variable, and buffer up packets until your buffer exceeds the length, at which point you decompress the entire buffer up to that length, and dispatch it to the handler, and repeat.
