### ISSUE TITLE
pymysql is missing after following installing instructions

### ISSUE THREAD

**Issue by kaijianwang** [DMOJ/judge#320]
After following all actions in [this section](https://docs.dmoj.ca/en/latest/site/installation/#installing-prerequisites), an ImportError of missing pymysql is thrown. 
Is there any missing dependency in requirements.txt?

(dmojsite) oj@ubuntu://home/oj/judge/site$ python manage.py check
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    import pymysql
ImportError: No module named pymysql

**Comment by quantum5** [comment]
Did you read the instructions?

>Install Python dependencies into the virtualenv.
>```
>(dmojsite) $ pip install -r requirements.txt
>(dmojsite) $ pip install mysqlclient
>```

Did you run `pip install mysqlclient`? No.

Also, this is the wrong repository.
