### ISSUE TITLE
Connection refused when run dmoj 127.0.0.1 -c configfile -p 8111

### ISSUE THREAD

**Issue by chenxuefei123** [DMOJ/judge#323]
I'm using python virtual env to run dmoj in ubuntu 16.04.  dmoj-cli works fine and i can submit judge and get expected results:
> dmoj-cli -c judge_conf.yml

However, in the same enviroment, I want to start dmoj  server in 127.0.0.1:8111. But see connection refused. Probably I got wrong understanding on the design. So dmoj is run a server or it tries to connect some server? Please clarify. 
> dmoj 127.0.0.1 -p 8111 -c judge_conf.yml 

It complains:
INFO 2018-05-10 14:33:19,798 11213 packet Preparing to connect to [127.0.0.1]:8111 as: LaiJudge
INFO 2018-05-10 14:33:19,798 11213 packet TLS not enabled.
/home/xuefei/judge-server/problems
INFO 2018-05-10 14:33:19,799 11213 packet Opening connection to: [127.0.0.1]:8111
ERROR 2018-05-10 14:33:19,800 11213 packet Connection failed due to socket error: [127.0.0.1]:8111
Traceback (most recent call last):
  File "/home/xuefei/code/judge/dmoj/packet.py", line 120, in _do_reconnect
    self._connect()
  File "/home/xuefei/code/judge/dmoj/packet.py", line 84, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
WARNING 2018-05-10 14:33:19,800 11213 packet Attempting reconnection in 4s: [127.0.0.1]:8111

**Comment by chenxuefei123** [comment]
never mind. I found the answer after reading: https://github.com/DMOJ/site/judge/bridge/judgeserver.py

**Comment by liaocs2008** [comment]
@chenxuefei123 Hi, may I ask how did you solve the problem?
