### ISSUE TITLE
Self-test should test output echoing

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#34]

**Comment by quantum5** [comment]
I guess that makes sense considering there have been cases where I added a language and input doesn't work.

**Comment by Xyene** [comment]
This has been implemented for a very long time, and most executors do test echoing now.

**Comment by quantum5** [comment]
Yes: `print 'echo: Hello, World!'` is totally echoing.

**Comment by Xyene** [comment]
Well, the functionality to do so is there. The will to actually test obscure languages? Not so much.
