### ISSUE TITLE
Is there an instruction to follow to add other options of languages?

### ISSUE THREAD

**Issue by SchrodingerZhu** [DMOJ/judge#355]
Such as `dotty` ans `elixir`

**Comment by Xyene** [comment]
There's no docs, but https://github.com/DMOJ/judge/tree/master/dmoj/executors should be a good starting point. Adding an executor is pretty easy; just find an executor similar to what you're trying to add, and modify it to your needs. Executors are autodetected from that directory.

For instance, for `dotty` you'd probably take https://github.com/DMOJ/judge/blob/master/dmoj/executors/SCALA.py (the autoconfig section is not necessary, it's just used for `dmoj-autoconfig`).

In the case of `elixir`, I recall we had issues in running Erlang as a whole under the current sandboxing structure (which makes some assumptions that online judging runtimes don't `fork` frequently, and are largely single-process -- which Erlang violates). Your mileage may vary on that one.

**Comment by SchrodingerZhu** [comment]
I am doing various test on different languages. Both `ghc-8.6.2` and `crystal` will throw an error like
`Protection fault on: 291 (sys_epoll_create1)`. So how to losen some restrictions for these kind of lanuages?

**Comment by kiritofeng** [comment]
I believe that means that the syscall `sys_epoll_create1` is being blocked by the sandbox. You can allow it by adding a `syscalls` array in the executor, like in [the Racket executor](https://github.com/DMOJ/judge/blob/master/dmoj/executors/RKT.py#L14).

**Comment by SchrodingerZhu** [comment]
solved!
