### ISSUE TITLE
Newer Scala IR Error.

### ISSUE THREAD

**Issue by SchrodingerZhu** [DMOJ/judge#356]
My server info:
```
Scala 2.12.7
openjdk-8-jdk
Ubuntu 16.04 (docker)
```
I write a program to print `hello, world`
```
object Main extends App {
  println("hello, world")
}
```
It is okay if I run the program by myself. But the judging result is `IR`.

And if I update Scala to `2.13.0-M5`, the result will become `WA`.

**Comment by Xyene** [comment]
I believe for Scala automatic classname extraction is not implemented, so your `object` name should be the same as the problem code for the judge to run your code correctly.
