### ISSUE TITLE
_normalize does not append a trailing newline to the last line of an input file if it is missing

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/judge#375]
By the POSIX definition of line, this renders the data invalid.

**Comment by Xyene** [comment]
The fact that data is bad exists is :notlikeblob:, but we should still do something about it.

**Comment by xiaowuc1** [comment]
there's a weird niche edge case where there is no input - in this case, the input should actually be an empty string and not a single blank line which is worth differentiating against the case where the input is a single blank line
