### ISSUE TITLE
Long Brain**** submissions (~28000 bytes or more) may receive a compile error

### ISSUE THREAD

**Issue by int-y1** [DMOJ/judge#383]
Submission 1161142 and 878558 are examples.

Previously, 878558 compiled correctly, but it received a compile error after a rejudge.

Submissions that exceed 65536 bytes are not allowed.

**Comment by Xyene** [comment]
This seems to have been fixed in https://github.com/DMOJ/judge/commit/aca6733a7312979e3bd81fe1d3aad7e065e80410 (the referenced submissions compile again now).
