### ISSUE TITLE
default path of problems added by site interface

### ISSUE THREAD

**Issue by kenneth-l-i** [DMOJ/judge#394]
I found that the problems test data and yml file added by the site interface will saved to dmoj site folder.
Is it correct? 
Is there any way to change the default path?
Since I config the dmoj to scan the site folder for problems, the dmoj is very unstable. May be the site folder is very large.
Then I reconfig the dmoj to scan another path (e.g. /home/myproblems) it become usable.

**Comment by AkitakiKou** [comment]
Has anybody come up with a solution with this? As the number of problems grew, the site directory quickly became cluttered by these test data directories, which made it quite a mess to maintain. I don't see any revelant options configurable in the example `local_settings.py` file provided in the docs.

**Comment by kenneth-l-i** [comment]
https://github.com/DMOJ/site/issues/880#issuecomment-459560551
