### ISSUE TITLE
Judges none available while judge connected

### ISSUE THREAD

**Issue by ZiYiBear** [DMOJ/judge#399]
I tried to installed the site and judge, and both install success. The url is on https://judge.mlc.app/
The site show all normal, and the judge also shows is connected
![image](https://user-images.githubusercontent.com/17896080/54469387-3b978200-47d2-11e9-8aa4-464bbcf01d93.png)
And When I create a problem, is shows none available judge 
![image](https://user-images.githubusercontent.com/17896080/54469401-726d9800-47d2-11e9-8d8e-d99ecb88b1a2.png)

the judge info show as below

![image](https://user-images.githubusercontent.com/17896080/54469437-e90a9580-47d2-11e9-9646-d3d6a353f1bd.png)

I cant figure out why, Please help

**Comment by Xyene** [comment]
This sounds to me like you've misconfigured `problem_storage_root`.

**Comment by ZiYiBear** [comment]
Thanks, it works!

> This sounds to me like you've misconfigured `problem_storage_root`. In particular, if you have:
> 
> ```yaml
> problem_storage_root:
> - /mnt/problems
> ```
> 
> ...then the problem `a003` should be in `/mnt/problems/a003`, and `/mnt/problems/a003/init.yml` must exist.

thanks, it works!
