### ISSUE TITLE
Statically link compiled submissions

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#417]
We should consider statically linking native submissions, allowing for smaller variability in memory usages across different `libc` and `libstdc++`/`libc++` versions.

Some stats courtesy of @quantum5:

```
quantum@osmium:~$ g++ mem.cpp -o mem_dynamic
quantum@osmium:~$ g++ -static mem.cpp -o mem_static
quantum@osmium:~$ ./mem_dynamic 
VmPeak:       13068 kB
VmSize:       13068 kB
VmLck:           0 kB
VmPin:           0 kB
VmHWM:        1580 kB
VmRSS:        1580 kB
VmData:         292 kB
VmStk:         132 kB
VmExe:           8 kB
VmLib:        4372 kB
VmPTE:          48 kB
VmPMD:          12 kB
VmSwap:           0 kB
quantum@osmium:~$ ./mem_static 
VmPeak:        1892 kB
VmSize:        1892 kB
VmLck:           0 kB
VmPin:           0 kB
VmHWM:           4 kB
VmRSS:           4 kB
VmData:         196 kB
VmStk:         132 kB
VmExe:        1548 kB
VmLib:           8 kB
VmPTE:          16 kB
VmPMD:           8 kB
VmSwap:           0 kB
```

Notably, the dynamic libraries are included in `VmRSS`, whereas static libraries are not. The judges report `VmHWM` (max `VmRSS`) as memory usage, so this change would allow compiled languages to consistently use 1~2mb less memory.

Roadmap:

* [ ] C++ 0x/11/14/17 (GCC and Clang)
* [ ] C 99/11
* [ ] Pascal
* [ ] Ada
* [ ] Clozure Common Lisp
* [ ] COBOL
* [ ] D
* [ ] Fortran
* [ ] Forth
* [x] Go -- static by default
* [ ] Haskell
* [ ] INTERCAL
* [ ] NASM
* [ ] Objective-C
* [ ] OCaml
* [ ] Pike
* [ ] Prolog
* [ ] Rust
* [ ] Scala
* [ ] Swift
* [ ] Turing
* [ ] Brain\*\*\*\*

**Comment by sorenbug** [comment]
Scala can be statically compiled using Scala Native. This will allow for much less resource usage and much faster execution speed (leveling the playing field for it).

**Comment by sorenbug** [comment]
Has the issue of Scala Native been addressed or should I open a separate issue for it? @Xyene
