### ISSUE TITLE
JVM sandbox refactor

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#42]
Following the .NET sandbox example, the JVM sandbox should have a similar interface to ease the addition of #37, #38, #39, #41.

**Comment by quantum5** [comment]
```python
class Executor(CLRExecutor):
    extension = 'cs'
    compiler = 'csc'
```

is just too good.

**Comment by Xyene** [comment]
Rhino/Nashorn (#41, #43) might be able to run through ptbox `jrunscript` without too much trouble. Maybe. At the same time, both are accessible through JSR 223, but would require a dedicated mode in the Java executor (or alternatively, a loader class).

**Comment by Xyene** [comment]
Adding `javax.script` support in the Java executor would also allow for the trivial addition of any JVM runtime that supports it (Rhino, Nashorn, JRuby, Jython etc)

**Comment by Xyene** [comment]
```java
ScriptEngineManager manager = new ScriptEngineManager();
ScriptEngine engine = manager.getEngineByName("..."); // (jruby|rhino|nashorn)
Bindings bindings = new SimpleBindings();
bindings.put("ONLINE_JUDGE", true);
String script = "puts $ONLINE_JUDGE"; // or print(ONLINE_JUDGE) with rhino/nashorn
engine.eval(script, bindings);
```

**Comment by quantum5** [comment]
Was more thinking in the lines of Scala and Groovy execution.

**Comment by Xyene** [comment]
`ScriptEngineManager.eval` wraps exceptions thrown by an interpreter in a `ScriptException`. This makes it really easy to write a "fake" submission along these lines:

```java
public class ScriptSubmission {
	public static void main(String[] argv) throws Throwable {
		String language = ...; // Obtain language somehow
		String script = ...; // Obtain script source somehow
		try {
			ScriptEngineManager manager = new ScriptEngineManager();
			ScriptEngine engine = manager.getEngineByName(language); // (jruby|rhino|nashorn)
			Bindings bindings = new SimpleBindings();
			bindings.put("ONLINE_JUDGE", true);
			engine.eval(script, bindings);
		} catch (ScriptException e) {
			throw e.getCause(); // Unwrap interpreter exception
		}
	}
}
```

This class can be hacked into https://github.com/DMOJ/judge/blob/master/java_executor/src/ca/dmoj/java/JavaSafeExecutor.java#L129, and that would add support for all JVM script languages, past, present, and future.

**Comment by quantum5** [comment]
Refactor is successful. Now just what you do with it...
