### ISSUE TITLE
Erlang support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#45]

**Comment by quantum5** [comment]
I installed Erlang on Herculaneum but I can't even use it right...

**Comment by quantum5** [comment]
Erlang uses `fork`. What do you want me to do?

**Comment by quantum5** [comment]
RabbitMQ experience from DMOJ/site#183 suggests that Erlang runs in a background server that is either global or per-user I don't know... We can't handle this with our judge structure.
