### ISSUE TITLE
checker improvement: make floats checker use arbitrary-precision Decimal

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/judge#456]
Most floating-point checkers do not depend on this, however it can avoid issues when the precision guarantee needed is very tight.

**Comment by Xyene** [comment]
I feel like the "fast path" for this (10e-6?) should use regular floats for speed, and switch to `Decimal` when needed.

**Comment by xiaowuc1** [comment]
Adding a flag that defaults to `fast` and uses floats in that case, and the `Decimal` otherwise seems like a reasonable approach.
