### ISSUE TITLE
Option to run system checks without sandbox

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#47]
For [DMOJ/hephaestus](https://github.com/DMOJ/hephaestus) to work, we have to have the option of running all the executors without the sandbox. Ideally this would mean migrating most duplicate executor features into `ResourceProxy` and renamed `BaseExecutor`. This `BaseExecutor` would then be able to expose the basic features as seen fit.

**Comment by quantum5** [comment]
#30

**Comment by quantum5** [comment]
With #49 we can simply have a flag to switch `launch` to `launch_unsafe`.

**Comment by Xyene** [comment]
Done.
