### ISSUE TITLE
C++ code doesn't run when iostream is included

### ISSUE THREAD

**Issue by swapnilbanga** [DMOJ/judge#470]
On initial setup, everything seemed to work fine, but now I am not able to run code in C++. Error message is not helpful either. Python and C are unaffected.
This is what I am submitting 

```
#include <iostream>
using namespace std;

int main() {
   int a;
   cin >> a;
   cout << a;
   return 0;
}
```
and this is the error:
Compiler runtime error, info: {"error": 0, "signal": 9, "result": 2, "exit_code": 0, "real_time": 11004, "cpu_time": 1, "memory": 2187264}

If I remove iostream and use stdio (with required changes in code), the submission is accepted.

**Comment by Xyene** [comment]
That error message is not from DMOJ. A quick Google search shows it pops up in [**QingdaoU/JudgeServer**](https://github.com/QingdaoU/JudgeServer/blob/b62c76c5c56375cc399d6187c64329bccf0914f1/server/compiler.py#L43). Did you perhaps mean to file this ticket there?
