### ISSUE TITLE
Error in setting up DMOJ judge on osx

### ISSUE THREAD

**Issue by erdumbledore** [DMOJ/judge#474]
Hi. I am trying to setup DMOJ site and judge in osx. Unfortunately, I don't have a Windows and Linux machine to set it up(Docs mention Windows and Linux installation steps). If I do `pip install dmoj`, it gives me the following error. I would really appreciate if someone could tell me the steps/dependencies to setup the project.

OS : macOS Mojave - 10.14.5
Python version: 3.7.0

```
In file included from /private/var/folders/d7/dtz_zy9d30l96qxg2qzvv5nm0000gn/T/pip-install-f5645ktw/dmoj/dmoj/cptbox/ptbox.h:44:
    /private/var/folders/d7/dtz_zy9d30l96qxg2qzvv5nm0000gn/T/pip-install-f5645ktw/dmoj/dmoj/cptbox/ext_linux.h:4:19: error: use of undeclared identifier 'PTRACE_TRACEME'
        return ptrace(PTRACE_TRACEME, 0, NULL, NULL);
                      ^
    1 error generated.
    error: command 'clang' failed with exit status 1
```

**Comment by WallE256** [comment]
Hi,
Unfortunately the judge is not supported on OSX due to Apple not completely implementing `ptrace` even if in BSD it is implemented. Therefore, supporting OSX is not really possible due to not being compatible with the current sandbox.

**Comment by erdumbledore** [comment]
@WallE256 Thanks for the prompt response. I noticed that there is a Dockerfile in the repo. Tried running it with Docker, but that failed too! The base docker image is 'minimal Debian GNU/Linux 8 (Jessie) Docker image'. 
Does running the repo using Docker depend on the base os(osx in my case) ? My understanding is that Docker makes the setup independent of the base os. Or am I wrong ?
I was planning to use the repo on an ec2 instance with [Amazon Linux AMI](https://aws.amazon.com/amazon-linux-ami/). Do you know if the repo builds on Amazon Linux ?

**Comment by Xyene** [comment]
@erdumbledore We don't support the Dockerfile in this repository, though the judge itself (not the site) should be easy to set up on most Unixes even without Docker. You can either install it from `pip` or from this repository (see the README.md), and follow the [Linux installation instructions](https://docs.dmoj.ca/en/latest/judge/linux_installation/).
