### ISSUE TITLE
Getting fatal error

### ISSUE THREAD

**Issue by diwakarvats** [DMOJ/judge#483]
Hi
When i run the command python setup.py develop i am getting the fatal error as 
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from dmoj/cptbox/_cptbox.cpp:654:
dmoj/cptbox/ptbox.h:29:10: fatal error: seccomp.h: No such file or directory
 #include <seccomp.h>
          ^~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Can you please help out to resolve this issue.

Thanks & Regards
Diwakar

**Comment by kiritofeng** [comment]
Either install seccomp (`libseccomp-dev` on most Linux distros), or set the variable `DMOJ_USE_SECCOMP="no"`
