### ISSUE TITLE
Fully class-based executor system

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#49]
The current executor system does not take advantage of inheritance and modularization. This should be changed so that small changes doesn't have to cause all executors to be changed, e.g. #47, #34.

**Comment by quantum5** [comment]
Example of the new, better executor system:

```python
class Executor(CompiledExecutor):
    ext = '.hs'
    name = 'HASK'
    fs = ['.*\.so', '/usr/']
    command = env['runtime'].get('ghc')
    syscalls = ['getpid', 'getppid', 'clock_getres', 'timer_create', 'timer_settime',
                'timer_delete', 'newselect']
    test_program = '''\
main = do
    a <- getContents
    putStr a
'''

    def get_compile_args(self):
        return [self.get_command(), '-O', '-o', self.problem, self._code]
```

**Comment by Xyene** [comment]
Outstanding executors:

* NASM
* RKT
* VC
* FS is somewhere in-between

**Comment by quantum5** [comment]
All the `.NET` executors are kinda sketchy.

**Comment by quantum5** [comment]
`NASM` and `RKT` have been turned.
