### ISSUE TITLE
"\w+\.exe has stopped working" on OLE on Windows

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#5]
![OLE](https://sc-cdn.scaleengine.net/i/020ff2018b20fd376c86186f198242a7.png)

```
Using checker standard
judge-connect.dmoj.ca:15000 => {
    "name": "grading-begin",
    "submission-id": 52896
}
OLE: stdout

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by quantum5** [comment]
Might have something to do with `wbox`'s implementation of `kill` and `wait`.

**Comment by Xyene** [comment]
The above commit prevents the error dialog from being shown, but the judge still terminates with 

```This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.```

**Comment by quantum5** [comment]
There is nothing you can do about that unless the call to `abort()` is prevented.

**Comment by Xyene** [comment]
I would've thought that apparent, given the description of `SetErrorMode`. The commit was not meant to fix the issue, but rather keep it from being annoying. Under no means does `SetErrorMode` fix the underlying bug that caused the window in the first place.

**Comment by quantum5** [comment]
Apparently setting `Software\Microsoft\Windows\Windows Error Reporting\DontShowUI` and `Software\Microsoft\Windows\Windows Error Reporting\Disabled` both to `1` under `HKCU` or `HKLM` hives will disable WER for good. May be we should give it a try!

**Comment by quantum5** [comment]
@Xyene Did you use the new `_wbox.pyd` with your change yesterday?

**Comment by FatalEagle** [comment]
Still broken!

**Comment by Xyene** [comment]
When a process is spawned with `CreateProcessWithLogonW`, it's a child of the Secondary Logon Service so the inheritable call to `SetErrorMode` on the judge is useless.

This issue is fixed by calling `SetErrorMode` in the submission through the injected DLL used in #136.
