### ISSUE TITLE
Clang

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#51]
According to [some StackOverflow post](http://stackoverflow.com/a/8208827/1090657), Clang is recommended for students due to "extremely clear diagnostics are definitely easier for beginners to interpret". The idea is rather popular to the point that [GCC tries to debunk it as a myth](https://gcc.gnu.org/wiki/ClangDiagnosticsComparison).

It might be worth to add `clang` as an alternative C/C++ frontend.

**Comment by FatalEagle** [comment]
If they can't figure out why their code is broken from getting the line number, they don't belong on an online judge anyway.

**Comment by quantum5** [comment]
Forgot to mention clang claims compile faster and with less memory
