### ISSUE TITLE
Rust runtime should show `rustc` versions

### ISSUE THREAD

**Issue by Jess3Jane** [DMOJ/judge#534]
As can be seen on many pages ([example](https://dmoj.ca/runtimes/matrix/)) the current behavior when talking about the rust runtime is to show the version of `cargo` but this is nearly useless. A much better approach would be to list the version of `rustc` the server supports as this actually informs what language features you have available.

The version of `rustc` used should also be updated from whatever version it's currently running as a fair few things have changed since early 2018. Ideally this should track `rustc` stable (currently 1.38) as this is what most people will expect.

**Comment by Xyene** [comment]
Thanks for reporting!

I've fixed this in #536, and it'll be reflected on the site after it is merged. I've also updated the Rust version on [dmoj.ca](https://dmoj.ca) to 1.38.

> Ideally this should track `rustc` stable (currently 1.38) as this is what most people will expect.

While we try to keep runtimes recently up-to-date, always tracking the latest version of > 50 fast-moving languages requires manpower we unfortunately don't have.
