### ISSUE TITLE
How to run a custom judge(seed2)

### ISSUE THREAD

**Issue by kitakaze0804** [DMOJ/judge#571]
I'm interested in interactive judge and tried to run [seed2](https://github.com/DMOJ/docs/tree/master/problem_examples/interactive/seed2) in the sample problem. I set `init.yml`, but the judge result is `TLE`. What should I do?

**Comment by kitakaze0804** [comment]
The latest source code was pulled and executed. Then, an unclear result of `SC` was returned.
Also, the following error occurred in `bridge.stderr.log`.
```
Traceback (most recent call last):
  File "/home/kitakaze/dmoj/site/judge/bridge/judgehandler.py", line 192, in packet
    handler(data)
  File "/home/kitakaze/dmoj/site/judge/bridge/judgecallback.py", line 328, in on_test_case
    super(DjangoJudgeHandler, self).on_test_case(packet)
  File "/home/kitakaze/dmoj/site/judge/bridge/judgehandler.py", line 252, in on_test_case
    logger.info('%s: %d test case(s) completed on: %s', self.name, len(packet['cases']), packet['submission-id'])
KeyError: 'cases'
```

**Comment by Xyene** [comment]
When updating the judge you also need to update the site, and restart the bridge. The error you are seeing is because the newer judge has a protocol change the bridge cannot understand.

**Comment by kitakaze0804** [comment]
When I tried it, I was able to judge correctly with Python, but not with Java. Is it impossible except for Python?

**Comment by Xyene** [comment]
No, it should be possible in Java. What's the source of the program you are submitting?

**Comment by kitakaze0804** [comment]
I thought a lot, but this time I rewrote the source you wrote in Python.
```Java
import java.util.*;
public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String result;
        int lo = 1;
    	int hi = 2000000000;
    	int num;
        while(lo < hi) {
        	num = (lo + hi) / 2;
        	System.out.println(num);
            result = sc.nextLine();
        	if(result.equals("FLOATS")) {
        		hi = num;
        	}
        	else if(result.equals("SINKS")) lo = num + 1;
        	else break;
        }
    }
}
```

**Comment by Xyene** [comment]
The variables `lo`/`hi`/`num` need to be declared `long` or they will overflow during the halving step, leading to a TLE on case 2 which tests this.

**Comment by kitakaze0804** [comment]
I tried to declare it as long type, but it doesn't change.
I mean, the result is all `TLE`.

**Comment by Xyene** [comment]
Ah, I see. Uncomment this line:

https://github.com/DMOJ/docs/blob/master/problem_examples/interactive/seed2/init.yml#L2

I'm not sure why it's commented in the docs; it shouldn't be. Setting `unbuffered` makes submissions line-buffered (which is slower, but necessary for interactive problems). Alternatively, you can add explicit `System.out.flush()` calls.

**Comment by kitakaze0804** [comment]
Finally, I did it!
Thank you very much.
<img title="seed2" src="https://user-images.githubusercontent.com/44520200/67740996-0c7d0a80-fa5b-11e9-909a-5a219d5f22b5.png" width="50%">

**Comment by kitakaze0804** [comment]
By the way, in this case, can't you set up test cases from the site side?

**Comment by Xyene** [comment]
Glad to hear it! (Note: I just released [v2.0.0](https://github.com/DMOJ/judge/releases/tag/v2.0.0) on PyPI, since the latest PyPI release, v1.4.0, had the issue you experienced with interactors despite it being fixed in master.)

Regarding your question, interactors (and custom checkers) are rather privileged. If you were to `sys.exit(0)` from one, you would quit the judge itself. On one hand this makes them quite powerful (they can compile programs on the fly, so you can have cool problems like https://dmoj.ca/problem/quine); on the other, their access should be restricted to problemsetters who both know what they are doing, and which you trust.

On [dmoj.ca](https://dmoj.ca) we have well over a hundred contributors with problemsetter permissions, and the site testdata management interface is geared towards their use-case. That is, it doesn't expose anything that could be unsafe, like interactors or custom checkers.

**Comment by kitakaze0804** [comment]
Can't set up a test case on the page in the image below?
Can I rewrite `init.yml` directly?
<image src="https://user-images.githubusercontent.com/44520200/67742516-9d55e500-fa5f-11e9-8440-849ac4add13f.png" width="60%">

**Comment by Xyene** [comment]
No, you can't. If you add data manually, you should check the "Is manually managed" checkbox in the problem admin.

**Comment by kitakaze0804** [comment]
Should I write `init.yml` myself and copy it to the problem folder?

**Comment by Xyene** [comment]
For interactive problems or problems using custom checkers, yes. For others the site interface may be sufficient.

**Comment by Xyene** [comment]
Closing out this issue since the problem seems to be resolved.
