### ISSUE TITLE
Errno 10013 after abnormal termination on Windows

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#6]
```socket.error: [Errno 10013] An attempt was made to access a socket in a way for
idden by its access permissions```

After exiting from the issue documented in #5 , Windows judges are not able to connect again.

**Comment by Xyene** [comment]
Firewall rule is not cleaned up, since the process exited abnormally.

![...](https://sc-cdn.scaleengine.net/i/af58496c491cfa73a943a28a8e0fef2a.png)

**Comment by quantum5** [comment]
You are supposed to use a private python installation for executing submissions exactly for this reason.

**Comment by quantum5** [comment]
Solution: implement `wbox` global function which you are supposed to call before you connect to bridge on windows. The function will remove wbox firewall rules.

**Comment by quantum5** [comment]
Design context: was expecting the firewall to terminate your connection on sight. Did not know it was possible to use same python installation and actually work.

**Comment by quantum5** [comment]
Another reason why a separate python is recommended is that `ctypes` can be deleted in that version to reduce attack surface.

**Comment by Xyene** [comment]
Does not excuse the fact that the user's firewall settings are left in a mangled state.

**Comment by quantum5** [comment]
I see a race condition in the proposed fix. What if we run two instances of the judge? The second will inevitably remove the first's block, causing it to fail horribly on clean up not to say that it will let the submission running loose.

**Comment by Xyene** [comment]
Cause is duplicate of #20.
