### ISSUE TITLE
chroot grading support

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#64]
We provide our own entry executable, perform `sudo setcap cap_sys_chroot+ep` on it, and then the judge is now capable of `chroot`ing. In `cptbox`, we can then drop the cap after `fork` and `chroot`.

A possible use of this is to run a specific grader inside a chroot, which can be easily shipped as a binary package. We can also set up exotic environments with `debootstrap` etc. for maximum fun.

Obviously this is not a trivial job and might not be worth it.

**Comment by Xyene** [comment]
This isn't going to happen.
