### ISSUE TITLE
Signature graders can't fdopen or close stdin/stdout

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/judge#65]
It causes an RTE. Maybe an easier solution is to change all graders to use a secret UUID instead of disallowing stdin/stdout.

**Comment by FatalEagle** [comment]
Another solution is to disable `exit(0);`, however I'm not sure how viable that is.

**Comment by Xyene** [comment]
All submissions are now allowed `dup2` and `dup3` (one of which `fdopen` undoubtedly uses) as part of #77, so this should no longer cause RTEs.

Secret UUIDs remain a good way to do this, though.
