### ISSUE TITLE
Removal of C++0x as a supported language

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#66]
All our judges are C++11-capable, except for the ancient rhcloud judges. C++0x was added provisionally until our servers improved, which they have.

The C++0x executor should not be deleted (in case someone installing the DMOJ has a similar situation), but it should not be enabled by default.

@quantum5 @FatalEagle

**Comment by quantum5** [comment]
The question remains whether to update all C++0x to C++11 on the site. It must be done if we delete the Language from the site.

**Comment by Xyene** [comment]
Alternatively we *could* just leave existing submissions untouched, but never connect a C++0x-enabled judge.

**Comment by Xyene** [comment]
We don't run C++0x judges any longer.

**Comment by quantum5** [comment]
C++0x judges are still up and submissions exist.

**Comment by Xyene** [comment]
All C++0x submissions have been converted to C++11.
