### ISSUE TITLE
Scheme support via CHICKEN

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#68]
The implementation of #16 went poorly, but [CHICKEN](http://www.call-cc.org/) appears to be a good alternative solution.

> CHICKEN is a compiler for the Scheme programming language. CHICKEN produces portable and efficient C, supports almost all of the R5RS Scheme language standard, and includes many enhancements and extensions. CHICKEN runs on Linux, MacOS X, Windows, and many Unix flavours.

The fact that it transpiles into C should make sandboxing a breeze.

**Comment by quantum5** [comment]
Not [this other Chicken](https://esolangs.org/wiki/Chicken).

**Comment by Xyene** [comment]
Appears to be working.
