### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#69]
It'll happen eventually.

http://openjdk.java.net/projects/jdk9/
https://jdk9.java.net/download/

**Comment by quantum5** [comment]
Installing JDK 9 snapshot in Herculaneum...

**Comment by quantum5** [comment]
```
quantum@herculaneum:~$ /opt/jdk1.9.0/bin/java -version
java version "1.9.0-ea"
Java(TM) SE Runtime Environment (build 1.9.0-ea-b68)
Java HotSpot(TM) Client VM (build 1.9.0-ea-b68, mixed mode)
```

**Comment by Xyene** [comment]
According to <http://openjdk.java.net/projects/jdk9/>, Java 9 will be feature-complete in 3 days.

**Comment by Xyene** [comment]
It's there and it works. Why you'd want to use Java 9 over Java 8 for contest programming is beyond me, but the executor works.
