### ISSUE TITLE
RFC: changing JAVA id to JAVA7

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#71]

**Comment by FatalEagle** [comment]
It's perfectly consistent, C++ isn't listed as C++03.

**Comment by Xyene** [comment]
On the other hand, we have PY2/PY3, PYPY2/PYPY3, RUBY21. C++ releases come along less often than Java (or Python) releases. There's an inconsistency somewhere.

**Comment by FatalEagle** [comment]
Solution: add Python 1.X and remove Ruby altogether (useless language that nobody ever submits).

**Comment by quantum5** [comment]
The fact that C++ is not listed as C++03 is rather confusing in itself, and should not be served as an example.

**Comment by quantum5** [comment]
Then again, we don't expect Java 7 to stay forever... May be some languages should be kept for historical purposes only and prohibit new submissions.

**Comment by Xyene** [comment]
We can expect Java 7 to stay for a *long*, *long* time. Just look at how
long Java 6 remained mainstream, even after the release of Java 7.

**Comment by quantum5** [comment]
According to that logic, we will eventually have JAVA7, JAVA8, JAVA9, JAVA10, ..., JAVA99, at which point the current 6 character language key limit breaks down.

**Comment by Xyene** [comment]
Done.

**Comment by quantum5** [comment]
What about C? There is C11 now as well, in addition to the C99 we have as `C`.
