### ISSUE TITLE
Alternative Java compiler support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#76]
* `sjavac` support has the potential to replace `javac` in the future. Even if not made publicly available immediately, it'll have to be implemented sooner or later.
* `ecj` has the ability to compile syntactically wrong code as long as its not invoked, which would alleviate some grievances of Java contest programmers.

**Comment by quantum5** [comment]
This is trivial if Java executor is implemented like all the executors in #49. We can just have `JavacExecutor`, `SjavacExecutor`, `ECJExecutor`.

**Comment by Xyene** [comment]
I'd advocate `SJavacExecutor` over `SjavacExecutor` for the sake of consistency.

**Comment by Xyene** [comment]
No longer feeling the allure of executor spam, and #42 makes this easy enough if any hoster of DMOJ wants an `ecj`/`sjavac` compiler option. `sjavac` might make it as part of #69.

**Comment by quantum5** [comment]
OH NO! TUDOR RESISTED TEH ALLURE!!!1!1!
