### ISSUE TITLE
Allow more syscalls by default

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#77]
While the principle of minimal privilege is good, we allow many complex syscalls by default, like `sys_fcntl`, but not `sys_getpid` or `sys_clock_getres`. We should allow more reasonable syscalls by default so many executors don't have to declare all those syscalls.

**Comment by Xyene** [comment]
Syscalls aggregated from all executors:

```python
{'timer_delete', 'select', 'getppid', 'sched_get_priority_min', 'getgroups32', 
'sched_getscheduler', 'sched_get_priority_max', 'timer_settime', 'clock_getres', 
'modify_ldt', 'timer_create', 'newselect', 'dup2', 'sched_getaffinity', 'sched_getparam',
 'getpid'}
```

**Comment by Xyene** [comment]
We should also provide sensible disallows, like `disallow_socket` so we're not stuck writing something like

```python
def handle_socket(debugger):
    def socket_return():
        debugger.result = -errno.EACCES
    debugger.syscall = debugger.getpid_syscall
    debugger.on_return(socket_return)
    return True
```

every time.

**Comment by Xyene** [comment]
Finally, we should also allow more of the filesystem by default. Things like `/dev/urandom` should be accessible to any language.

**Comment by quantum5** [comment]
`/proc/\d+/cmdline$` is not that good of an idea. You don't want the judge's command line read for example.

**Comment by quantum5** [comment]
May be we can have tuples for the individual syscalls in that list, with optional handlers for it, so we can do:

```python
syscalls = [..., ('socketcall', syscall_error(EACCES)), ...]
```

**Comment by Xyene** [comment]
This is done, and many executors are greatly simplified as a result.
