### ISSUE TITLE
Batch counter

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#81]
The judge must now handle batch numbering on its own. #80 and DMOJ/site#183 makes it impossible for the bridge to number batches.

Batches will be numbered with natural numbers, while non-batched cases will be numbered zero.

**Comment by quantum5** [comment]
Test cases should probably be numbered too since I can't imagine the site-side processing all responses in order.

**Comment by Xyene** [comment]
This is no longer relevant.
