### ISSUE TITLE
Scan recursively when searching for problem directories

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#82]

**Comment by Xyene** [comment]
I'm reopening this, in light of both the permission and organization benefits it would provide. For one, we can stop having massive directories containing 15 years of CCC (90 problems, theoretically) and simply have 15 subfolders, one for each year.

This also plays nicely with OneDrive's permissions, allowing us to assign people to work on adding a specific CCC year without allowing access &mdash; and enabling accidental destruction &mdash; of the rest of the problems.

**Comment by quantum5** [comment]
I don't like the recursion, though I do offer an alternative.

```yaml
problem_storage_root:
  - 1: /problems/ccc
```

This means all first level subdirectories of `/problems/ccc` should be treated as a problem root.

**Comment by BinAccel** [comment]
Implemented as of #250 . Leaving ticket open for feedback.
