### ISSUE TITLE
TEXT submissions

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#87]
Seems really sketchy to submit output-only answers as PHP...

**Comment by FatalEagle** [comment]
A sketchy method for a sketchy language.

**Comment by quantum5** [comment]
Obviously we should add a language called `CAT`, that runs, umm, `cat`!

**Comment by Xyene** [comment]
```python
from .base_executor import ScriptExecutor
from judgeenv import env


class Executor(ScriptExecutor):
    ext = '.txt'
    name = 'TEXT'
    command = env['runtime'].get('cat', '/bin/cat')
    test_program = 'echo: Hello, World!\n'
    fs = ['.*\.(?:so|txt)']
    syscalls = ['fadvise64_64']

initialize = Executor.initialize
```

It's been on Herculaneum for a while now.

**Comment by quantum5** [comment]
Simply install `cat` on Windows!

Note: the Windows-equivalent of `cat` is `type`, which is less a command, and more a `cmd.exe` builtin.
