### ISSUE TITLE
Option to use heap size to determine MLE for C/++

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#88]

**Comment by quantum5** [comment]
`VmData` in `/proc/<pid>/status` seems to provide such information, but it has to be polled.

**Comment by quantum5** [comment]
Also since we have basically unlimited stack size for submissions, they can simply `alloca` to bypass all memory limits if we do this.

**Comment by quantum5** [comment]
This will result in memory limit circumvention through the stack.
