### ISSUE TITLE
Should we "fake" Java memory usage?

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#89]
We use heap size for MLE, but display total memory usage. This confuses people, so perhaps we should display max heap usage instead. Thoughts?

**Comment by quantum5** [comment]
That seems to give Java an unfair footing in memory usage.

**Comment by Xyene** [comment]
Not necessarily, since it would display the memory used by the user, not the arbitrary memory used by the JVM. Besides, this wouldn't impact rankings too much since Java's Object overhead would even out any discrepancies (Java would still rank below most native solutions).

**Comment by quantum5** [comment]
Irrelavent. I don't think we can choose to display Java heap usage now that we are using `cptbox` to populate execution time and memory.

**Comment by Xyene** [comment]
You still can, the same way we send exception data... That it may be faked
is nonetheless sketchy.
