### ISSUE TITLE
Unicode toggling for Java executor

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#9]
To speed up IO in Java, the executor uses an ASCII-encoded stream. This has the effect of making Unicode-dependent problems such as http://www.dmoj.ca/problem/denoun2 painful to solve in Java.

The stream encoding should be configurable per-problem.

**Comment by quantum5** [comment]
We should probably generalize this into an additional but ignorable parameter passing mechanism for executors.

**Comment by Xyene** [comment]
This is implemented.
