### ISSUE TITLE
Final class breaks Java regex

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#90]
``` java
final public class Test {
```

is accepted, but

``` java
public final class Test {
```

is not.

**Comment by quantum5** [comment]
Are there more possible modifiers and possible orders?

**Comment by Xyene** [comment]
`public abstract class`, `abstract public class`, but not `public abstract final class`, `abstract public final class`, `public final abstract class`... you get the idea.

**Comment by Xyene** [comment]
Also `strictfp`.

**Comment by quantum5** [comment]
Umm, this will be very hard... Can `public abstract class` have `main`?

**Comment by Xyene** [comment]
Yes.

**Comment by quantum5** [comment]
Damn. This will be a nightmare. I can just feel I still would have a nightmare 10 years later.

**Comment by Xyene** [comment]
We could consider using an actual parser that generates an AST: definitely much more reliable and future-proof!

**Comment by quantum5** [comment]
We could, but is it worth it?

**Comment by Xyene** [comment]
This nightmare appears to be too immersing for @quantum5 to wake up from.

**Comment by quantum5** [comment]
What do you speak of, [dream-thing](http://runescape.wikia.com/wiki/Transcript:One_of_a_Kind#The_Queen_Black_Dragon)? Permutations of keywords, some valid, and others not? No, I name you nightmare thing. You bring me thoughts I do not wish to dream! But speak, nightmare-thing, give a list of all possible permutations, and there may yet be hope for you. Else, begone, and I shall dream of destroying you. *The Queen Black Dragon gathers her strength to breathe extremely hot flames.*
