### ISSUE TITLE
seccomp grading support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#96]
Though restrictive, seccomp grading should not be highly difficult to implement, and would provide a major performance boost to some languages that compile down to the native level (i.e., no runtime loading of files like Python).

> seccomp allows a process to make a one-way transition into a "secure" state where it cannot make any system calls except exit(), sigreturn(), read() and write() to already-open file descriptors.

Something to consider. Implementation would be easy, since it's just a one-way `prctl` call. It's also easy to implement a basic `cptbox`-like equivalent, sans custom handlers:

http://blog.yadutaf.fr/2014/05/29/introduction-to-seccomp-bpf-linux-syscall-filter/

**Comment by quantum5** [comment]
What was the original reason for not using seccomp? RHEL kernel too old? OpenVZ kernel too old?

**Comment by Xyene** [comment]
I think it was the RHEL kernel, but it's been so long I can hardly remember.

**Comment by quantum5** [comment]
I think I remember now. I don't think support for `seccomp` with `pf` filters is enabled by default in most kernel builds.

**Comment by Xyene** [comment]
All these years later, have we ever actually experienced performance issues with our judges, in the real world?

Since we haven't, I'm closing this ticket since it appears to be a lot of work for not a lot of benefit.
