### ISSUE TITLE
Missing syscall sys_setup

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#99]

**Comment by quantum5** [comment]
This is a lie. There is no `sys_setup`. Syscall `0` is `sys_restart_syscall`.

**Comment by Xyene** [comment]
For what it's worth, historically syscall 0 *[was sys_setup](http://linux.die.net/man/2/setup)*, though this changed in 2.1.121.

**Comment by quantum5** [comment]
For our purposes, if the process is using syscall `0`, it is doing `sys_restart_syscall`.

**Comment by Xyene** [comment]
Nowadays yes, though the circumstances that led to the creation of this issue were iffy (since an application can't call `sys_restart_syscall` by itself), and only some obscure language which I've since forgotten had issues with it, likely while doing dubious things with signals.
